/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: a7068c3ac1bc816b17cb5fcdd7999f34)
interface __BaseEnv_Env {
	RAW_ARCHIVE: R2Bucket;
	AUTHENTICATED_SECRETS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	PROCESSING_QUEUE: Queue;
	WEB_OPERATOR_QUEUE: Queue;
	BROWSER: BrowserRun;
	ASSETS: Fetcher;
	PUBLIC_API_BASE_URL: string;
	PUBLIC_WEB_BASE_URL: string;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_AI_GATEWAY_ID: string;
	OPENAI_MODEL: string;
	DISTILLED_WEB_OPERATOR_ENABLED: string;
	DISTILLED_BROWSER_BACKEND: string;
	DISTILLED_LLM_MODE: string;
	DISTILLED_LLM_API_GATEWAY: string;
	DISTILLED_MODEL_CALL_TIMEOUT_MS: string;
	DISTILLED_RUN_SETTLEMENT_RESERVE_MS: string;
	WEB_OPERATOR_RUNTIME_URL: string;
	EMAIL_FROM: string;
	APIFY_GOOGLE_NEWS_ACTOR_ID: string;
	APIFY_X_ACTOR_ID: string;
	APIFY_LINKEDIN_COMPANY_ACTOR_ID: string;
	APIFY_LINKEDIN_PROFILE_ACTOR_ID: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_API_BASE_URL" | "PUBLIC_WEB_BASE_URL" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_ID" | "OPENAI_MODEL" | "DISTILLED_WEB_OPERATOR_ENABLED" | "DISTILLED_BROWSER_BACKEND" | "DISTILLED_LLM_MODE" | "DISTILLED_LLM_API_GATEWAY" | "DISTILLED_MODEL_CALL_TIMEOUT_MS" | "DISTILLED_RUN_SETTLEMENT_RESERVE_MS" | "WEB_OPERATOR_RUNTIME_URL" | "EMAIL_FROM" | "APIFY_GOOGLE_NEWS_ACTOR_ID" | "APIFY_X_ACTOR_ID" | "APIFY_LINKEDIN_COMPANY_ACTOR_ID" | "APIFY_LINKEDIN_PROFILE_ACTOR_ID">> {}
}
