import { AuthenticatedProfileError,type AuthAuditEvent,type AuthenticatedProfileOwnershipPolicy,type AuthenticatedProfileRepository,type AuthenticatedSiteProfile,type CredentialProfile,type SecretBlobStore } from "@distilled/agent-runtime";

type Row=Record<string,unknown>;
export class R2AuthenticatedSecretStore implements SecretBlobStore{
  constructor(private readonly bucket:R2Bucket){}
  async put(ref:string,ciphertext:Uint8Array){await this.bucket.put(ref,ciphertext,{httpMetadata:{contentType:"application/vnd.distilled.encrypted-profile+json"},customMetadata:{encrypted:"aes-256-gcm",containsSecrets:"true"}})}
  async get(ref:string){const object=await this.bucket.get(ref);return object?new Uint8Array(await object.arrayBuffer()):null}
  async delete(ref:string){await this.bucket.delete(ref)}
}
export class D1AuthenticatedProfileRepository implements AuthenticatedProfileRepository{
  constructor(private readonly db:D1Database){}
  async createCredentialProfile(v:CredentialProfile){await this.db.prepare(`INSERT INTO credential_profiles(id,tenant_id,owner_id,site_family,authentication_method,encrypted_credential_ref,created_at,updated_at,revoked_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(v.id,v.tenantId,v.ownerId,v.siteFamily,v.authenticationMethod,v.encryptedCredentialRef,v.createdAt,v.updatedAt,v.revokedAt??null).run()}
  async createSiteProfile(v:AuthenticatedSiteProfile){await this.db.prepare(`INSERT INTO authenticated_site_profiles(id,tenant_id,owner_id,site_family,allowed_origins_json,permission_scope,authentication_method,credential_profile_id,encrypted_session_ref,session_state,version,created_at,updated_at,last_validated_at,expires_at,reauth_reason,revoked_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(...profileValues(v)).run()}
  async getCredentialProfile(id:string){const r=await this.db.prepare("SELECT * FROM credential_profiles WHERE id=?").bind(id).first<Row>();return r?credential(r):null}
  async getSiteProfile(id:string){const r=await this.db.prepare("SELECT * FROM authenticated_site_profiles WHERE id=?").bind(id).first<Row>();return r?profile(r):null}
  async updateSiteProfile(v:AuthenticatedSiteProfile){const result=await this.db.prepare(`UPDATE authenticated_site_profiles SET allowed_origins_json=?,permission_scope=?,authentication_method=?,credential_profile_id=?,encrypted_session_ref=?,session_state=?,version=?,updated_at=?,last_validated_at=?,expires_at=?,reauth_reason=?,revoked_at=? WHERE id=? AND tenant_id=? AND owner_id=? AND version<?`).bind(JSON.stringify(v.allowedOrigins),v.permissionScope,v.authenticationMethod,v.credentialProfileId??null,v.encryptedSessionRef??null,v.sessionState,v.version,v.updatedAt,v.lastValidatedAt??null,v.expiresAt??null,v.reauthReason??null,v.revokedAt??null,v.id,v.tenantId,v.ownerId,v.version).run();if(Number(result.meta.changes??0)!==1){const existing=await this.getSiteProfile(v.id);if(!existing||existing.version!==v.version)throw new Error("authenticated profile stale version")}}
  async appendAuthAudit(v:AuthAuditEvent){await this.db.prepare(`INSERT OR IGNORE INTO authenticated_profile_audit(id,profile_id,tenant_id,run_id,event_type,from_state,to_state,safe_metadata_json,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM authenticated_site_profiles WHERE id=? AND tenant_id=?)`).bind(v.id,v.profileId,v.tenantId,v.runId??null,v.type,v.fromState??null,v.toState??null,JSON.stringify(v.safeMetadata),v.createdAt,v.profileId,v.tenantId).run()}
}
export class D1AccountTenantOwnershipPolicy implements AuthenticatedProfileOwnershipPolicy{
  constructor(private readonly db:D1Database){}
  async assertActiveOwner(input:{tenantId:string;ownerId:string}){if(input.tenantId!==input.ownerId)throw new AuthenticatedProfileError("AUTH_TENANT_OWNER_MISMATCH");const row=await this.db.prepare("SELECT disabled_at FROM accounts WHERE id=?").bind(input.ownerId).first<Row>();if(!row)throw new AuthenticatedProfileError("AUTH_OWNER_NOT_FOUND");if(row.disabled_at)throw new AuthenticatedProfileError("AUTH_OWNER_DISABLED");}
}
function profileValues(v:AuthenticatedSiteProfile){return[v.id,v.tenantId,v.ownerId,v.siteFamily,JSON.stringify(v.allowedOrigins),v.permissionScope,v.authenticationMethod,v.credentialProfileId??null,v.encryptedSessionRef??null,v.sessionState,v.version,v.createdAt,v.updatedAt,v.lastValidatedAt??null,v.expiresAt??null,v.reauthReason??null,v.revokedAt??null]}
function credential(r:Row):CredentialProfile{return{id:String(r.id),tenantId:String(r.tenant_id),ownerId:String(r.owner_id),siteFamily:String(r.site_family),authenticationMethod:r.authentication_method as CredentialProfile["authenticationMethod"],encryptedCredentialRef:String(r.encrypted_credential_ref),createdAt:String(r.created_at),updatedAt:String(r.updated_at),revokedAt:r.revoked_at?String(r.revoked_at):undefined}}
function profile(r:Row):AuthenticatedSiteProfile{return{id:String(r.id),tenantId:String(r.tenant_id),ownerId:String(r.owner_id),siteFamily:String(r.site_family),allowedOrigins:JSON.parse(String(r.allowed_origins_json)),permissionScope:r.permission_scope as AuthenticatedSiteProfile["permissionScope"],authenticationMethod:r.authentication_method as AuthenticatedSiteProfile["authenticationMethod"],credentialProfileId:r.credential_profile_id?String(r.credential_profile_id):undefined,encryptedSessionRef:r.encrypted_session_ref?String(r.encrypted_session_ref):undefined,sessionState:r.session_state as AuthenticatedSiteProfile["sessionState"],version:Number(r.version),createdAt:String(r.created_at),updatedAt:String(r.updated_at),lastValidatedAt:r.last_validated_at?String(r.last_validated_at):undefined,expiresAt:r.expires_at?String(r.expires_at):undefined,reauthReason:r.reauth_reason?String(r.reauth_reason):undefined,revokedAt:r.revoked_at?String(r.revoked_at):undefined}}
