import type { Env,AuthenticatedProfileBootstrapMessage } from "./types";
import { executeAuthenticatedProfileBootstrap,type AuthenticatedProfileBootstrapInput } from "./authenticated-profile-bootstrap";

type TriggerEnv=Pick<Env,"DB"|"WEB_OPERATOR_QUEUE"|"BROWSER"|"AUTHENTICATED_SECRETS"|"AUTH_PROFILE_ENCRYPTION_KEYS"|"AUTH_PROFILE_ACTIVE_KEY_ID"|"DISTILLED_BROWSER_BACKEND">;
type Row={request_id:string;operation:string;profile_id:string;expected_profile_version:number;tenant_id:string;owner_id:string;state:string;attempt_budget:number;attempt_count:number;expires_at:string};
export type BootstrapTriggerResult={status:"ignored"|"completed"|"failed"|"expired";requestId:string;outcomeState?:string;failureCode?:string};

export async function dispatchPendingAuthenticatedProfileBootstraps(env:Pick<Env,"DB"|"WEB_OPERATOR_QUEUE">,now=new Date()):Promise<number>{
  const timestamp=now.toISOString();
  await env.DB.prepare(`UPDATE authenticated_profile_bootstrap_requests SET state='expired',completed_at=?,failure_code='REQUEST_EXPIRED' WHERE state IN ('pending','queued') AND expires_at<=?`).bind(timestamp,timestamp).run();
  const rows=await env.DB.prepare(`SELECT request_id FROM authenticated_profile_bootstrap_requests WHERE operation='AUTHENTICATION_BOOTSTRAP' AND state='pending' AND expires_at>? AND attempt_count<attempt_budget ORDER BY created_at,request_id LIMIT 10`).bind(timestamp).all<{request_id:string}>();
  let count=0;for(const row of rows.results){await env.WEB_OPERATOR_QUEUE.send({type:"authenticated_profile_bootstrap",requestId:row.request_id} satisfies AuthenticatedProfileBootstrapMessage);const result=await env.DB.prepare(`UPDATE authenticated_profile_bootstrap_requests SET state='queued',queued_at=? WHERE request_id=? AND state='pending' AND expires_at>?`).bind(timestamp,row.request_id,timestamp).run();if(Number(result.meta.changes)===1)count++;}return count;
}

export async function processAuthenticatedProfileBootstrap(env:TriggerEnv,message:AuthenticatedProfileBootstrapMessage,now=new Date(),execute:(input:AuthenticatedProfileBootstrapInput,env:Env,requestId:string)=>Promise<Response>=(input,runtimeEnv,requestId)=>executeAuthenticatedProfileBootstrap(input,runtimeEnv,{bootstrapRequestId:requestId})):Promise<BootstrapTriggerResult>{
  const timestamp=now.toISOString();
  const claim=await env.DB.prepare(`UPDATE authenticated_profile_bootstrap_requests SET state='running',started_at=?,attempt_count=attempt_count+1,browser_generation=1 WHERE request_id=? AND operation='AUTHENTICATION_BOOTSTRAP' AND state IN ('pending','queued') AND expires_at>? AND attempt_count<attempt_budget`).bind(timestamp,message.requestId,timestamp).run();
  if(Number(claim.meta.changes)!==1){const existing=await load(env.DB,message.requestId);return{status:existing?.state==="expired"?"expired":"ignored",requestId:message.requestId};}
  const row=await load(env.DB,message.requestId);if(!row)return{status:"ignored",requestId:message.requestId};
  const authorization=await env.DB.prepare(`SELECT p.id profile_id,p.version profile_version,p.tenant_id,p.owner_id,p.revoked_at,a.disabled_at FROM authenticated_site_profiles p JOIN accounts a ON a.id=p.owner_id WHERE p.id=?`).bind(row.profile_id).first<Record<string,unknown>>();
  const failure=!authorization?"PROFILE_OR_OWNER_MISSING":row.tenant_id!==row.owner_id?"TENANT_OWNER_MISMATCH":String(authorization.tenant_id)!==row.tenant_id||String(authorization.owner_id)!==row.owner_id?"PROFILE_OWNER_MISMATCH":Number(authorization.profile_version)!==row.expected_profile_version?"PROFILE_VERSION_MISMATCH":authorization.revoked_at?"PROFILE_REVOKED":authorization.disabled_at?"OWNER_DISABLED":undefined;
  if(failure)return finish(env.DB,row.request_id,"failed",timestamp,{failureCode:failure});
  let response:Response;try{response=await execute({authenticatedProfileId:row.profile_id,tenantId:row.tenant_id,ownerId:row.owner_id},env as Env,row.request_id)}catch{return finish(env.DB,row.request_id,"failed",new Date().toISOString(),{failureCode:"INTERNAL_EXECUTION_FAILURE"})}
  const body:Record<string,unknown>=await response.json<Record<string,unknown>>().catch(()=>({}));const diagnostic=isRecord(body.diagnostic)?body.diagnostic:{};const safe=safeDiagnostic(diagnostic);
  if(!response.ok)return finish(env.DB,row.request_id,"failed",new Date().toISOString(),{failureCode:stringValue(diagnostic.failureCode)??stringValue(body.error)??`HTTP_${response.status}`,safe});
  return finish(env.DB,row.request_id,"completed",new Date().toISOString(),{outcomeState:stringValue(body.status),outcomeReason:stringValue(body.reason),safe});
}

export async function cancelAuthenticatedProfileBootstrap(db:D1Database,requestId:string,now=new Date()):Promise<boolean>{const result=await db.prepare(`UPDATE authenticated_profile_bootstrap_requests SET state='cancelled',completed_at=? WHERE request_id=? AND state IN ('pending','queued')`).bind(now.toISOString(),requestId).run();return Number(result.meta.changes)===1;}
async function load(db:D1Database,id:string){return db.prepare(`SELECT request_id,operation,profile_id,expected_profile_version,tenant_id,owner_id,state,attempt_budget,attempt_count,expires_at FROM authenticated_profile_bootstrap_requests WHERE request_id=?`).bind(id).first<Row>();}
async function finish(db:D1Database,id:string,state:"completed"|"failed",at:string,input:{outcomeState?:string;outcomeReason?:string;failureCode?:string;safe?:Record<string,string|number|boolean>}){await db.prepare(`UPDATE authenticated_profile_bootstrap_requests SET state=?,outcome_state=?,outcome_reason=?,failure_code=?,safe_diagnostic_json=?,completed_at=? WHERE request_id=? AND state='running' AND attempt_count=1`).bind(state,input.outcomeState??null,input.outcomeReason??null,input.failureCode??null,JSON.stringify(input.safe??{}),at,id).run();return{status:state,requestId:id,outcomeState:input.outcomeState,failureCode:input.failureCode} as BootstrapTriggerResult;}
function safeDiagnostic(value:Record<string,unknown>){const allowed=["lastSuccessfulStage","failureStage","failureCode","surfaceKind","hostname","pathnameCategory","pathnamePattern","authOriginValid","loginModalPresent","formPresent","identifierTextboxPresent","identifierTextboxRole","identifierTextboxType","identifierTextboxInsideForm","identifierControlFocused","identifierControlHasAssociatedFormSubmit","buttonCountCategory","linkCountCategory","submitControlPresent","submitControlEnabled","knownIdentifierSubmitLabel","continueControlPresent","passwordTextboxPresent","usePasswordControlPresent","verificationInputPresent","otpInputCountCategory","captchaWidgetPresent","securityVerificationSurfacePresent","mandatoryVerificationControlPresent","authenticatedNavigationPresent","profileVersion","browserBackend","browserGeneration","elapsedMs"];const result:Record<string,string|number|boolean>={};for(const key of allowed){const item=value[key];if(typeof item==="string"||typeof item==="number"||typeof item==="boolean")result[key]=item;}return result;}
function isRecord(value:unknown):value is Record<string,unknown>{return!!value&&typeof value==="object"&&!Array.isArray(value)}function stringValue(value:unknown){return typeof value==="string"?value:undefined}
