import { AuthenticatedProfileError,type AuthenticationChallengeRecord,type AuthenticationChallengeState,type AuthenticationChallengeStore,type AuthAuditEvent,type AuthenticatedProfileOwnershipPolicy,type AuthenticatedProfileRepository,type AuthenticatedSiteProfile,type CredentialProfile,type SecretBlobStore } from "@distilled/agent-runtime";

type Row=Record<string,unknown>;
export class R2AuthenticatedSecretStore implements SecretBlobStore{
  constructor(private readonly bucket:R2Bucket){}
  async put(ref:string,ciphertext:Uint8Array){await this.bucket.put(ref,ciphertext,{httpMetadata:{contentType:"application/vnd.distilled.encrypted-profile+json"},customMetadata:{encrypted:"aes-256-gcm",containsSecrets:"true"}})}
  async get(ref:string){const object=await this.bucket.get(ref);return object?new Uint8Array(await object.arrayBuffer()):null}
  async delete(ref:string){await this.bucket.delete(ref)}
}
export class D1AuthenticatedProfileRepository implements AuthenticatedProfileRepository{
  constructor(private readonly db:D1Database){}
  async createCredentialProfile(v:CredentialProfile){await this.db.prepare(`INSERT INTO credential_profiles(id,tenant_id,owner_id,site_family,authentication_method,encrypted_credential_ref,created_at,updated_at,revoked_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(v.id,v.tenantId,v.ownerId,v.siteFamily,v.authenticationMethod,v.encryptedCredentialRef,v.createdAt,v.updatedAt,v.revokedAt??null).run()}
  async createSiteProfile(v:AuthenticatedSiteProfile){await this.db.prepare(`INSERT INTO authenticated_site_profiles(id,tenant_id,owner_id,site_family,allowed_origins_json,permission_scope,authentication_method,credential_profile_id,encrypted_session_ref,session_state,version,created_at,updated_at,last_validated_at,expires_at,reauth_reason,revoked_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING`).bind(...profileValues(v)).run()}
  async getCredentialProfile(id:string){const r=await this.db.prepare("SELECT * FROM credential_profiles WHERE id=?").bind(id).first<Row>();return r?credential(r):null}
  async getSiteProfile(id:string){const r=await this.db.prepare("SELECT * FROM authenticated_site_profiles WHERE id=?").bind(id).first<Row>();return r?profile(r):null}
  async updateSiteProfile(v:AuthenticatedSiteProfile){const result=await this.db.prepare(`UPDATE authenticated_site_profiles SET allowed_origins_json=?,permission_scope=?,authentication_method=?,credential_profile_id=?,encrypted_session_ref=?,session_state=?,version=?,updated_at=?,last_validated_at=?,expires_at=?,reauth_reason=?,revoked_at=? WHERE id=? AND tenant_id=? AND owner_id=? AND version<?`).bind(JSON.stringify(v.allowedOrigins),v.permissionScope,v.authenticationMethod,v.credentialProfileId??null,v.encryptedSessionRef??null,v.sessionState,v.version,v.updatedAt,v.lastValidatedAt??null,v.expiresAt??null,v.reauthReason??null,v.revokedAt??null,v.id,v.tenantId,v.ownerId,v.version).run();if(Number(result.meta.changes??0)!==1){const existing=await this.getSiteProfile(v.id);if(!existing||existing.version!==v.version)throw new Error("authenticated profile stale version")}}
  async appendAuthAudit(v:AuthAuditEvent){await this.db.prepare(`INSERT OR IGNORE INTO authenticated_profile_audit(id,profile_id,tenant_id,run_id,event_type,from_state,to_state,safe_metadata_json,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM authenticated_site_profiles WHERE id=? AND tenant_id=?)`).bind(v.id,v.profileId,v.tenantId,v.runId??null,v.type,v.fromState??null,v.toState??null,JSON.stringify(v.safeMetadata),v.createdAt,v.profileId,v.tenantId).run()}
}
export class D1AuthenticationChallengeStore implements AuthenticationChallengeStore{
  constructor(private readonly db:D1Database){}
  async create(v:AuthenticationChallengeRecord){await this.db.prepare(`INSERT OR IGNORE INTO authenticated_browser_challenges(challenge_id,run_id,bootstrap_request_id,tenant_id,owner_id,profile_id,profile_version,browser_generation,auth_flow_id,challenge_kind,challenge_phase,provider_kind,observed_at,expires_at,attempt_budget,attempt_number,state,provider_operation_id,elapsed_ms,resolution_outcome,subsequent_surface_kind,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(...challengeValues(v)).run();const saved=await this.get(v.challengeId);if(!saved)throw new Error("challenge did not persist");assertChallengeFences(saved,v);return saved}
  async get(id:string){const row=await this.db.prepare("SELECT * FROM authenticated_browser_challenges WHERE challenge_id=?").bind(id).first<Row>();return row?challenge(row):null}
  async transition(id:string,expected:readonly AuthenticationChallengeState[],update:Partial<AuthenticationChallengeRecord>){const current=await this.get(id);if(!current)throw new Error("challenge record unavailable");if(!expected.includes(current.state)){if(update.state===current.state)return current;throw new Error("challenge state conflict")}const next={...current,...update};const placeholders=expected.map(()=>"?").join(",");const result=await this.db.prepare(`UPDATE authenticated_browser_challenges SET attempt_number=?,state=?,provider_operation_id=?,elapsed_ms=?,resolution_outcome=?,subsequent_surface_kind=?,updated_at=? WHERE challenge_id=? AND state IN (${placeholders})`).bind(next.attemptNumber,next.state,next.providerOperationId??null,next.elapsedMs,next.resolutionOutcome??null,next.subsequentSurfaceKind??null,next.updatedAt,id,...expected).run();if(Number(result.meta.changes)!==1){const saved=await this.get(id);if(saved&&saved.state===next.state)return saved;throw new Error("challenge state conflict")}return next}
}
export class D1AccountTenantOwnershipPolicy implements AuthenticatedProfileOwnershipPolicy{
  constructor(private readonly db:D1Database){}
  async assertActiveOwner(input:{tenantId:string;ownerId:string}){if(input.tenantId!==input.ownerId)throw new AuthenticatedProfileError("AUTH_TENANT_OWNER_MISMATCH");const row=await this.db.prepare("SELECT disabled_at FROM accounts WHERE id=?").bind(input.ownerId).first<Row>();if(!row)throw new AuthenticatedProfileError("AUTH_OWNER_NOT_FOUND");if(row.disabled_at)throw new AuthenticatedProfileError("AUTH_OWNER_DISABLED");}
}
function profileValues(v:AuthenticatedSiteProfile){return[v.id,v.tenantId,v.ownerId,v.siteFamily,JSON.stringify(v.allowedOrigins),v.permissionScope,v.authenticationMethod,v.credentialProfileId??null,v.encryptedSessionRef??null,v.sessionState,v.version,v.createdAt,v.updatedAt,v.lastValidatedAt??null,v.expiresAt??null,v.reauthReason??null,v.revokedAt??null]}
function credential(r:Row):CredentialProfile{return{id:String(r.id),tenantId:String(r.tenant_id),ownerId:String(r.owner_id),siteFamily:String(r.site_family),authenticationMethod:r.authentication_method as CredentialProfile["authenticationMethod"],encryptedCredentialRef:String(r.encrypted_credential_ref),createdAt:String(r.created_at),updatedAt:String(r.updated_at),revokedAt:r.revoked_at?String(r.revoked_at):undefined}}
function profile(r:Row):AuthenticatedSiteProfile{return{id:String(r.id),tenantId:String(r.tenant_id),ownerId:String(r.owner_id),siteFamily:String(r.site_family),allowedOrigins:JSON.parse(String(r.allowed_origins_json)),permissionScope:r.permission_scope as AuthenticatedSiteProfile["permissionScope"],authenticationMethod:r.authentication_method as AuthenticatedSiteProfile["authenticationMethod"],credentialProfileId:r.credential_profile_id?String(r.credential_profile_id):undefined,encryptedSessionRef:r.encrypted_session_ref?String(r.encrypted_session_ref):undefined,sessionState:r.session_state as AuthenticatedSiteProfile["sessionState"],version:Number(r.version),createdAt:String(r.created_at),updatedAt:String(r.updated_at),lastValidatedAt:r.last_validated_at?String(r.last_validated_at):undefined,expiresAt:r.expires_at?String(r.expires_at):undefined,reauthReason:r.reauth_reason?String(r.reauth_reason):undefined,revokedAt:r.revoked_at?String(r.revoked_at):undefined}}
function challengeValues(v:AuthenticationChallengeRecord){return[v.challengeId,v.runId,v.bootstrapRequestId,v.tenantId,v.ownerId,v.profileId,v.profileVersion,v.browserGeneration,v.authFlowId,v.challengeKind,v.challengePhase,v.providerKind,v.observedAt,v.expiresAt,v.attemptBudget,v.attemptNumber,v.state,v.providerOperationId??null,v.elapsedMs,v.resolutionOutcome??null,v.subsequentSurfaceKind??null,v.updatedAt]}
function challenge(r:Row):AuthenticationChallengeRecord{return{challengeId:String(r.challenge_id),runId:String(r.run_id),bootstrapRequestId:String(r.bootstrap_request_id),tenantId:String(r.tenant_id),ownerId:String(r.owner_id),profileId:String(r.profile_id),profileVersion:Number(r.profile_version),browserGeneration:Number(r.browser_generation),authFlowId:String(r.auth_flow_id),challengeKind:r.challenge_kind as AuthenticationChallengeRecord["challengeKind"],challengePhase:r.challenge_phase as AuthenticationChallengeRecord["challengePhase"],providerKind:String(r.provider_kind),observedAt:String(r.observed_at),expiresAt:String(r.expires_at),attemptBudget:Number(r.attempt_budget),attemptNumber:Number(r.attempt_number),state:r.state as AuthenticationChallengeRecord["state"],providerOperationId:r.provider_operation_id?String(r.provider_operation_id):undefined,elapsedMs:Number(r.elapsed_ms),resolutionOutcome:r.resolution_outcome?String(r.resolution_outcome):undefined,subsequentSurfaceKind:r.subsequent_surface_kind?String(r.subsequent_surface_kind):undefined,updatedAt:String(r.updated_at)}}
function assertChallengeFences(a:AuthenticationChallengeRecord,b:AuthenticationChallengeRecord){for(const key of ["runId","bootstrapRequestId","tenantId","ownerId","profileId","profileVersion","browserGeneration","authFlowId","challengeKind","providerKind","expiresAt"] as const)if(a[key]!==b[key])throw new Error("challenge fence mismatch")}
