import {AuthenticatedBrowserBridgeError,type AuthenticatedBrowserExecutionCapability,type PublicBrowserObservation} from "@distilled/agent-runtime";
import {CloudflareContainerBrowserBridgeTransport} from "./cloudflare-container-browser-transport";
import type {Env} from "./types";

type Input={sourceUrl:string;articlePathPrefix:string;maxArticles?:number};
export async function handlePublicBrowserAcquisition(request:Request,env:Env):Promise<Response>{
  if(request.method!=="POST"||!env.BRIDGE_PREFLIGHT_TOKEN)return Response.json({error:"not found"},{status:404});
  if((request.headers.get("authorization")??"").replace(/^Bearer\s+/i,"").trim()!==env.BRIDGE_PREFLIGHT_TOKEN)return Response.json({error:"unauthorized"},{status:401});
  if((env.DISTILLED_BROWSER_PROVIDER??"").trim().toLowerCase()!=="cloudflare_container"||!env.AUTHENTICATED_BROWSER_CONTAINER)return Response.json({error:"container_not_selected"},{status:409});
  const input=await request.json().catch(()=>null) as Partial<Input>|null;let source:URL;try{source=new URL(String(input?.sourceUrl??""));if(source.protocol!=="https:"||source.username||source.password)throw new Error()}catch{return Response.json({error:"invalid_source"},{status:400})}
  const prefix=String(input?.articlePathPrefix??"");if(!prefix.startsWith("/")||prefix.length>256)return Response.json({error:"invalid_article_path_prefix"},{status:400});
  const maxArticles=Math.min(20,Math.max(1,Number.isInteger(input?.maxArticles)?Number(input?.maxArticles):10));
  const runId=`public_browser_${crypto.randomUUID().replaceAll("-","")}`,capability:AuthenticatedBrowserExecutionCapability={bridgeExecutionId:runId,bootstrapRequestId:runId,runId,tenantId:"public_acquisition",ownerId:"public_acquisition",profileId:"public_acquisition",expectedProfileVersion:0,browserGeneration:1,authFlowId:`public_flow_${runId}`,siteKind:"PUBLIC",authEntryPoint:source.href,sessionProbeUrl:source.href,allowedOrigins:[source.origin],writeOrigins:[],issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+120_000).toISOString(),operationBudget:2+maxArticles*2};
  const transport=new CloudflareContainerBrowserBridgeTransport(env.AUTHENTICATED_BROWSER_CONTAINER);let sessionId:string|undefined;let closed=false;let stage:PublicBrowserStage="OPEN_AUTH_BROWSER";
  try{
    stage="OPEN_AUTH_BROWSER";const opened=await transport.execute({protocol:"v1",operationId:crypto.randomUUID(),capability,operation:"OPEN_AUTH_BROWSER"}) as {sessionId:string;runId:string;tenantId:string;generation:number};if(opened.runId!==runId||opened.tenantId!=="public_acquisition"||opened.generation!==1)throw new AuthenticatedBrowserBridgeError("BRIDGE_FENCE_MISMATCH");sessionId=opened.sessionId;
    stage="NAVIGATE_PUBLIC_PAGE";const listing=await navigateAndObserve(transport,capability,source.href,()=>{stage="OBSERVE_PUBLIC_PAGE"});const candidateUrls=[...new Set(listing.controls.map(control=>control.destinationUrl).filter((url):url is string=>typeof url==="string"&&sameOrigin(url,source)&&new URL(url).pathname.startsWith(prefix)))].slice(0,maxArticles);
    const articles:PublicBrowserObservation[]=[];for(const url of candidateUrls){stage="NAVIGATE_PUBLIC_PAGE";const observation=await navigateAndObserve(transport,capability,url,()=>{stage="OBSERVE_PUBLIC_PAGE"});if(observation.article)articles.push(observation)}
    await close();return Response.json({provider:"CLOUDFLARE_CONTAINER",browserBackend:"container",listing,articles,candidateUrlCount:candidateUrls.length,cleanup:true,synthetic:false});
  }catch(error){const failedStage=stage;const diagnostic=publicBrowserFailureDiagnostic(error,failedStage,closed);if(diagnostic.errorCode==="BRIDGE_NETWORK_POLICY_DENIED"&&diagnostic.policy)console.error("public_browser_policy_denial",publicBrowserPolicyLogFields(diagnostic));await close();return Response.json({...diagnostic,cleanup:closed},{status:502});}
  async function close(){if(sessionId&&!closed){closed=true;stage="CLOSE_AUTH_BROWSER";await transport.execute({protocol:"v1",operationId:crypto.randomUUID(),capability,operation:"CLOSE_AUTH_BROWSER"}).catch(()=>undefined);sessionId=undefined;}}
}
export type PublicBrowserStage="OPEN_AUTH_BROWSER"|"NAVIGATE_PUBLIC_PAGE"|"OBSERVE_PUBLIC_PAGE"|"CLOSE_AUTH_BROWSER";
export function publicBrowserPolicyLogFields(diagnostic:ReturnType<typeof publicBrowserFailureDiagnostic>){const policy=diagnostic.policy;return{event:"public_browser_policy_denial",operation:diagnostic.operation,policyRule:policy?.policyRule,deniedHostname:policy?.deniedHostname,redirectHop:policy?.redirectHop,provider:diagnostic.provider,browserBackend:diagnostic.browserBackend,cleanup:diagnostic.cleanup};}
export function publicBrowserFailureDiagnostic(error:unknown,stage:PublicBrowserStage,cleanup:boolean){const bridge=error instanceof AuthenticatedBrowserBridgeError?error:undefined;return{stage,operation:stage,errorCode:bridge?.code??"public_browser_acquisition_failed",...(bridge?.diagnostic&&"policyRule" in bridge.diagnostic?{policy:bridge.diagnostic}:{}),provider:"CLOUDFLARE_CONTAINER",browserBackend:"container",cleanup};}
async function navigateAndObserve(transport:CloudflareContainerBrowserBridgeTransport,capability:AuthenticatedBrowserExecutionCapability,url:string,onObserve:()=>void){await transport.execute({protocol:"v1",operationId:crypto.randomUUID(),capability,operation:"NAVIGATE_PUBLIC_PAGE",url});onObserve();return await transport.execute({protocol:"v1",operationId:crypto.randomUUID(),capability,operation:"OBSERVE_PUBLIC_PAGE"}) as PublicBrowserObservation;}
function sameOrigin(value:string,source:URL){try{return new URL(value).origin===source.origin}catch{return false}}
