import { assertCapabilityUsable,type AuthenticatedProfileCapability,type AuthenticatedProfileRepository,type AuthenticatedSessionState,type AuthenticatedProfileService,type BrowserSessionState,type CredentialMaterial } from "./auth-profile";
import type { BrowserExecutorPort,BrowserScope,StructuredBrowserUsePort } from "./browser";
export type AuthenticatedSiteDetection={state:AuthenticatedSessionState;reason:string};
export interface AuthenticatedSiteSnapshot{url:string;title:string;visibleText:string;controls:Array<{role?:string;label:string;type?:string}>}
export interface RuntimeAuthenticationBrowser{goto(url:string):Promise<void>;fill(selector:string,value:string):Promise<void>;click(selector:string):Promise<void>;snapshot():Promise<AuthenticatedSiteSnapshot>;importSession(state:BrowserSessionState):Promise<void>;exportSession():Promise<BrowserSessionState>}
export interface AuthenticatedSiteAdapter{readonly siteFamily:string;readonly allowedOrigins:readonly string[];readonly loginOrigin:string;detect(snapshot:AuthenticatedSiteSnapshot):AuthenticatedSiteDetection;bootstrap(browser:RuntimeAuthenticationBrowser,credential:CredentialMaterial):Promise<AuthenticatedSiteDetection>}
const X_CHALLENGE=/captcha|arkose|security key|unusual activity|suspicious login|verify (?:that )?you(?:'|’)re human/i;const X_MFA=/two-factor|authentication code|verification code|enter the code|check your email|check your phone/i;const X_LOGIN=/log in to x|sign in to x|enter your phone, email, or username/i;
export class XAuthenticatedSiteAdapter implements AuthenticatedSiteAdapter{
  readonly siteFamily="x";readonly allowedOrigins=["https://x.com","https://twitter.com"] as const;readonly loginOrigin="https://x.com";
  detect(snapshot:AuthenticatedSiteSnapshot):AuthenticatedSiteDetection{const text=`${snapshot.title}\n${snapshot.visibleText}`;const url=new URL(snapshot.url);if(!this.allowedOrigins.includes(url.origin as typeof this.allowedOrigins[number]))return{state:"CHALLENGE_REQUIRED",reason:"unexpected_origin"};if(X_CHALLENGE.test(text)||/\/account\/access/.test(url.pathname))return{state:"CHALLENGE_REQUIRED",reason:"x_security_challenge"};if(X_MFA.test(text)||/challenge/.test(url.pathname))return{state:"MFA_REQUIRED",reason:"x_human_verification"};if(X_LOGIN.test(text)||/\/i\/flow\/login/.test(url.pathname))return{state:"REAUTH_REQUIRED",reason:"x_login_required"};if(/\/home|\/explore|\/notifications|\/[^/]+\/status\//.test(url.pathname))return{state:"ACTIVE",reason:"x_authenticated_surface"};return{state:"SESSION_EXPIRED",reason:"x_authenticated_state_unconfirmed"};}
  async bootstrap(browser:RuntimeAuthenticationBrowser,credential:CredentialMaterial){await browser.goto("https://x.com/i/flow/login");let state=this.detect(await browser.snapshot());if(state.state==="MFA_REQUIRED"||state.state==="CHALLENGE_REQUIRED")return state;await browser.fill('input[autocomplete="username"]',credential.username);await browser.click('[role="button"]:has-text("Next")');state=this.detect(await browser.snapshot());if(state.state==="MFA_REQUIRED"||state.state==="CHALLENGE_REQUIRED")return state;await browser.fill('input[type="password"]',credential.password);await browser.click('[data-testid="LoginForm_Login_Button"]');return this.detect(await browser.snapshot());}
}
export const AUTHENTICATED_READ_ONLY_DENIED_ACTIONS=["post","reply","like","repost","follow","unfollow","direct_message","delete","settings","purchase","subscribe"] as const;
export function assertAuthenticatedReadOnlyAction(action:string){if(AUTHENTICATED_READ_ONLY_DENIED_ACTIONS.includes(action as typeof AUTHENTICATED_READ_ONLY_DENIED_ACTIONS[number]))throw new Error("authenticated profile is read-only");if(!["navigate","inspect","extract","scroll","follow_content_link"].includes(action))throw new Error("authenticated action is not allowlisted");}

export interface AuthenticatedBrowserExecutorPort extends BrowserExecutorPort,StructuredBrowserUsePort{
  exportAuthenticatedSession(scope:BrowserScope):Promise<BrowserSessionState>;
  attachAuthenticatedSession(scope:BrowserScope,state:BrowserSessionState):Promise<void>;
  detectAuthenticatedState(scope:BrowserScope,adapter:AuthenticatedSiteAdapter):Promise<AuthenticatedSiteDetection>;
  establishAuthenticatedSession(scope:BrowserScope,adapter:AuthenticatedSiteAdapter,credential:CredentialMaterial):Promise<AuthenticatedSiteDetection>;
}
export class AuthenticatedBrowserLifecycle{
  constructor(private readonly repository:AuthenticatedProfileRepository,private readonly profiles:AuthenticatedProfileService,private readonly browser:AuthenticatedBrowserExecutorPort,private readonly adapters:Map<string,AuthenticatedSiteAdapter>){}
  async attach(input:{capability:AuthenticatedProfileCapability;scope:BrowserScope;ownerId:string}){
    const profile=await this.repository.getSiteProfile(input.capability.profileId);if(!profile)throw new Error("authenticated profile unavailable");await this.profiles.assertActiveOwner(profile);const adapter=this.adapters.get(profile.siteFamily);if(!adapter)throw new Error("authenticated site adapter unavailable");assertCapabilityUsable(input.capability,profile,{tenantId:input.scope.tenantId,ownerId:input.ownerId,runId:input.scope.runId,browserGeneration:input.scope.generation,origin:adapter.loginOrigin});
    const saved=await this.profiles.loadSession(profile);if(saved){await this.browser.attachAuthenticatedSession(input.scope,saved);await this.browser.navigate(input.scope,adapter.loginOrigin==="https://x.com"?"https://x.com/home":adapter.loginOrigin);const detection=await this.browser.detectAuthenticatedState(input.scope,adapter);if(detection.state==="ACTIVE")return{profile,sessionReused:true,detection};await this.profiles.transition(profile,detection.state,{runId:input.scope.runId,reason:detection.reason});if(detection.state==="MFA_REQUIRED"||detection.state==="CHALLENGE_REQUIRED")return{profile,sessionReused:true,detection};}
    const credential=await this.profiles.loadCredential(profile);const detection=await this.browser.establishAuthenticatedSession(input.scope,adapter,credential);credential.username="";credential.password="";
    if(detection.state!=="ACTIVE"){await this.profiles.transition(profile,detection.state,{runId:input.scope.runId,reason:detection.reason});return{profile,sessionReused:false,detection};}
    const updated=await this.profiles.saveSession(profile,await this.browser.exportAuthenticatedSession(input.scope),{runId:input.scope.runId});return{profile:updated,sessionReused:false,detection};
  }
}
