import { AuthenticatedProfileError,assertCapabilityUsable,type AuthenticatedProfileCapability,type AuthenticatedProfileRepository,type AuthenticatedSessionState,type AuthenticatedProfileService,type BrowserSessionState,type CredentialMaterial } from "./auth-profile";
import { BrowserNavigationError,type BrowserExecutorPort,type BrowserScope,type StructuredBrowserUsePort } from "./browser";
import { makeId } from "./contracts";
import type { AuthenticationChallengeBinding,AuthenticationChallengeKind,ChallengeCoordinator } from "./challenge-coordinator";
export type AuthenticatedSiteDetection={state:AuthenticatedSessionState;reason:string;challengeKind?:AuthenticationChallengeKind;challengePhase?:"PRE_IDENTIFIER"|"POST_IDENTIFIER"|"PRE_PASSWORD"|"POST_PASSWORD"|"UNKNOWN";challengeProviderOutcome?:string};
export type AuthenticatedBootstrapStage="profile_resolved"|"browser_allocated"|"browser_context_initialized"|"credential_retrieved"|"credential_decrypted"|"navigation_started"|"navigation_completed"|"auth_surface_observed"|"identifier_surface_recognized"|"identifier_control_found"|"identifier_injected"|"identifier_post_injection_surface_observed"|"identifier_submit_control_detected"|"identifier_submitted"|"verification_surface_observed"|"password_alternative_detected"|"password_alternative_selected"|"password_surface_observed"|"password_control_found"|"password_injected"|"password_submitted"|"auth_state_classified"|"session_captured"|"session_encrypted"|"session_persisted";
export type AuthenticatedBootstrapFailureCode="CREDENTIAL_REFERENCE_MISSING"|"CREDENTIAL_DECRYPTION_FAILED"|"BROWSER_ALLOCATION_FAILED"|"BROWSER_CONTEXT_INITIALIZATION_FAILED"|"INITIAL_NAVIGATION_FAILED"|"NAVIGATION_TIMEOUT"|"UNEXPECTED_AUTH_ORIGIN"|"NETWORK_POLICY_DENIED"|"AUTH_SURFACE_TIMEOUT"|"UNRECOGNIZED_AUTH_SURFACE"|"IDENTIFIER_CONTROL_MISSING"|"IDENTIFIER_INJECTION_FAILED"|"IDENTIFIER_SUBMISSION_CONTROL_MISSING"|"IDENTIFIER_SUBMISSION_FAILED"|"PASSWORD_ALTERNATIVE_CONTROL_MISSING"|"PASSWORD_ALTERNATIVE_SELECTION_FAILED"|"PASSWORD_ROUTE_TRANSITION_FAILED"|"PASSWORD_CONTROL_MISSING"|"PASSWORD_INJECTION_FAILED"|"PASSWORD_SUBMISSION_FAILED"|"AUTH_STATE_CLASSIFICATION_FAILED"|"SESSION_CAPTURE_FAILED"|"SESSION_ENCRYPTION_FAILED"|"SESSION_PERSISTENCE_FAILED"|"BOOTSTRAP_INFRASTRUCTURE_FAILED";
export type AuthenticatedBootstrapSafeMetadata=Record<string,string|number|boolean|undefined>;
export interface AuthenticatedBootstrapObserver{stage(stage:AuthenticatedBootstrapStage,metadata?:AuthenticatedBootstrapSafeMetadata):Promise<void>}
export class AuthenticatedBootstrapError extends Error{constructor(public readonly code:AuthenticatedBootstrapFailureCode,public readonly stage:AuthenticatedBootstrapStage,public readonly safeMetadata:AuthenticatedBootstrapSafeMetadata={},options?:{cause?:unknown}){super(code,options);this.name="AuthenticatedBootstrapError";}}
export interface AuthenticatedSiteSnapshot{url:string;title:string;visibleText:string;formCountCategory?:CountCategory;controls:Array<{role?:string;label:string;type?:string;autocomplete?:string;insideForm?:boolean;disabled?:boolean;visible?:boolean;focusable?:boolean;focused?:boolean}>}
export interface RuntimeAuthenticationBrowser{goto(url:string,options?:{waitUntil?:"networkidle"|"domcontentloaded"}):Promise<void>;fill(selector:string,value:string):Promise<void>;fillControl(control:{role:"textbox";label:string},value:string):Promise<void>;click(selector:string):Promise<void>;clickControl(control:{role:"button"|"link";label:string}):Promise<void>;waitForAuthenticationSurface?():Promise<AuthenticatedSiteSnapshot>;waitForPasswordSurface?():Promise<void>;snapshot():Promise<AuthenticatedSiteSnapshot>;importSession(state:BrowserSessionState):Promise<void>;exportSession():Promise<BrowserSessionState>}
export interface AuthenticationFlowObservation{authFlowActive:boolean;authEntryPointKind:string;authFlowOrigin:string;sameOriginTransitionCount:number;authFlowLineageValid:boolean}
export interface AuthenticationFlowLineage{readonly entryPoint:{kind:string;url:string};start():Promise<AuthenticationFlowObservation>;observe(url:string):Promise<AuthenticationFlowObservation>;invalidate():void}
export interface AuthenticationFlowBinding{tenantId:string;ownerId:string;profileId:string;profileVersion:number;requestId:string;browserGeneration:number;browserContextId:string;allowedOrigins:readonly string[];expiresAt:string}
const INACTIVE_FLOW:AuthenticationFlowObservation={authFlowActive:false,authEntryPointKind:"NONE",authFlowOrigin:"",sameOriginTransitionCount:0,authFlowLineageValid:false};
export class RuntimeAuthenticationFlowLineage implements AuthenticationFlowLineage{
  private active=false;private valid=true;private transitions=0;private lastUrl="";
  constructor(public readonly entryPoint:{kind:string;url:string},private readonly binding:AuthenticationFlowBinding,private readonly validateAuthority:()=>Promise<boolean>){ }
  async start(){const entry=new URL(this.entryPoint.url);this.valid=this.binding.allowedOrigins.includes(entry.origin)&&this.binding.expiresAt>new Date().toISOString()&&await this.authorityValid();this.active=this.valid;this.lastUrl=this.active?entry.href:"";return this.state();}
  async observe(value:string){if(!this.active||!this.valid)return this.state();let url:URL;try{url=new URL(value)}catch{this.invalidate();return this.state()}const origin=new URL(this.entryPoint.url).origin;if(url.origin!==origin||!this.binding.allowedOrigins.includes(url.origin)||this.binding.expiresAt<=new Date().toISOString()||!await this.authorityValid()){this.invalidate();return this.state()}if(url.href!==this.lastUrl){this.transitions++;this.lastUrl=url.href}return this.state();}
  invalidate(){this.active=false;this.valid=false;}
  private async authorityValid(){try{return await this.validateAuthority()}catch{return false}}
  private state():AuthenticationFlowObservation{return{authFlowActive:this.active,authEntryPointKind:this.entryPoint.kind,authFlowOrigin:new URL(this.entryPoint.url).origin,sameOriginTransitionCount:this.transitions,authFlowLineageValid:this.active&&this.valid}}
}
export interface AuthenticationChallengeRuntime{coordinator:ChallengeCoordinator;binding:AuthenticationChallengeBinding;validateFences():Promise<boolean>;signal?:AbortSignal}
export interface AuthenticatedSiteAdapter{readonly siteFamily:string;readonly allowedOrigins:readonly string[];readonly authenticationNetworkOrigins?:readonly string[];readonly authenticationWriteOrigins?:readonly string[];readonly loginOrigin:string;readonly authenticationEntryPoint?:{kind:string;url:string};detect(snapshot:AuthenticatedSiteSnapshot):AuthenticatedSiteDetection;bootstrap(browser:RuntimeAuthenticationBrowser,credential:CredentialMaterial,observer?:AuthenticatedBootstrapObserver,lineage?:AuthenticationFlowLineage,challenges?:AuthenticationChallengeRuntime):Promise<AuthenticatedSiteDetection>}
export type XAuthenticationStep="IDENTIFIER_ENTRY"|"IDENTIFIER_ENTRY_READY"|"PASSWORD_ENTRY"|"AMBIGUOUS_PASSWORD_SURFACE"|"VERIFICATION_WITH_PASSWORD_ALTERNATIVE"|"MANDATORY_EMAIL_CODE"|"MANDATORY_SMS_CODE"|"MFA_REQUIRED"|"SECURITY_CHALLENGE"|"CAPTCHA"|"AUTHENTICATED"|"LOGIN_FAILED"|"UNEXPECTED_AUTH_STATE";
export type XAuthenticationSurfaceKind=XAuthenticationStep|"UNKNOWN";
export type XAuthenticationPathCategory="LOGIN_FLOW"|"X_AUTH"|"CHALLENGE_FLOW"|"ACCOUNT_ACCESS"|"AUTHENTICATED_APP"|"OTHER_X"|"FOREIGN"|"INVALID";
type CountCategory="none"|"one"|"few"|"many";
type KnownTextboxLabel="EMAIL"|"USERNAME"|"EMAIL_OR_USERNAME"|"IDENTIFIER"|"PASSWORD"|"VERIFICATION_CODE"|"UNKNOWN";
type KnownControlLabel="CONTINUE"|"NEXT"|"LOGIN"|"LOG_IN"|"SIGN_IN"|"USE_PASSWORD"|"FORGOT_PASSWORD"|"CANCEL"|"OTHER_KNOWN_AUTH";
export interface XAuthenticationSurfaceFingerprint{surfaceKind:XAuthenticationSurfaceKind;hostname:string;pathnameCategory:XAuthenticationPathCategory;pathnamePattern:string;authOriginValid:boolean;authFlowActive:boolean;authEntryPointKind:string;authFlowOrigin:string;sameOriginTransitionCount:number;authFlowLineageValid:boolean;identifierInjected:boolean;loginModalPresent:boolean;formPresent:boolean;formCountCategory:CountCategory;activeFormPresent:boolean;activeFormUnambiguous:boolean;textboxCountCategory:CountCategory;identifierTextboxCountCategory:CountCategory;passwordTextboxCountCategory:CountCategory;identifierTextboxPresent:boolean;identifierTextboxRole:"textbox"|"none";identifierTextboxType:"text"|"email"|"tel"|"other"|"none";identifierTextboxVisible:boolean;identifierTextboxEnabled:boolean;identifierTextboxFocusable:boolean;identifierTextboxInsideActiveForm:boolean;identifierTextboxInsideForm:boolean;identifierControlFocused:boolean;identifierControlHasAssociatedFormSubmit:boolean;passwordTextboxPresent:boolean;passwordTextboxVisible:boolean;passwordTextboxEnabled:boolean;passwordTextboxFocusable:boolean;passwordTextboxInsideActiveForm:boolean;passwordAutocompleteCategory:"CURRENT_PASSWORD"|"NEW_PASSWORD"|"OTHER"|"NONE";knownIdentifierTextboxLabel:KnownTextboxLabel;knownPasswordTextboxLabel:KnownTextboxLabel;knownControlLabels:readonly KnownControlLabel[];buttonCountCategory:CountCategory;linkCountCategory:CountCategory;submitControlPresent:boolean;submitControlVisible:boolean;submitControlEnabled:boolean;submitControlSemanticKind:"CONTINUE"|"NEXT"|"LOGIN"|"SIGN_IN"|"NONE";knownIdentifierSubmitLabel:"CONTINUE"|"NEXT"|"LOGIN"|"SIGN_IN"|"NONE";continueControlPresent:boolean;usePasswordControlPresent:boolean;verificationInputPresent:boolean;otpInputCountCategory:"none"|"one"|"multiple";captchaWidgetPresent:boolean;securityVerificationSurfacePresent:boolean;mandatoryVerificationControlPresent:boolean;authenticatedNavigationPresent:boolean}
const X_SECURITY_CHALLENGE=/arkose|security key|unusual activity|suspicious login|verify (?:that )?you(?:'|’)re human/i;const X_CAPTCHA=/captcha|arkose|turnstile|recaptcha/i;const X_EMAIL_CODE=/check your email|code (?:we )?sent to (?:your )?email|email verification code/i;const X_SMS_CODE=/check your phone|code (?:we )?sent (?:to your phone|by (?:text|sms))|sms code/i;const X_MFA=/two-factor|authentication code|authenticator app/i;const X_LOGIN_FAILED=/incorrect password|wrong password|could not log you in|login failed/i;
const X_DIRECT_PASSWORD_LABELS=["Use password","Use password instead","Log in with password"] as const;
const X_IDENTIFIER_LABELS=["Email or username","Phone, email, or username"] as const;const X_CONTINUE_LABELS=["Continue","Next","Log in","Sign in"] as const;const X_VERIFICATION_LABELS=["Verification code","Code","Enter code","Authentication code"] as const;
const X_SAFE_PATH_SEGMENTS=new Set(["i","flow","login","challenge","account","access","home","explore","notifications","settings","compose","search","status"]);
export class XAuthenticatedSiteAdapter implements AuthenticatedSiteAdapter{
  readonly siteFamily="x";readonly allowedOrigins=["https://x.com","https://twitter.com"] as const;readonly loginOrigin="https://x.com";readonly authenticationEntryPoint={kind:"X_LOGIN",url:"https://x.com/login"} as const;
  readonly authenticationNetworkOrigins=[...this.allowedOrigins,"https://api.x.com","https://api.twitter.com","https://abs.twimg.com","https://pbs.twimg.com","https://ton.twimg.com","https://video.twimg.com","https://syndication.twitter.com"] as const;
  readonly authenticationWriteOrigins=["https://x.com","https://twitter.com","https://api.x.com","https://api.twitter.com"] as const;
  fingerprint(snapshot:AuthenticatedSiteSnapshot,flow:AuthenticationFlowObservation=INACTIVE_FLOW,identifierInjected=false):XAuthenticationSurfaceFingerprint{
    let url:URL|undefined;try{url=new URL(snapshot.url)}catch{}
    const authOriginValid=!!url&&this.allowedOrigins.includes(url.origin as typeof this.allowedOrigins[number]);const pathnameCategory=this.pathnameCategory(url,authOriginValid);const pathnamePattern=this.pathnamePattern(url,authOriginValid);
    const authSurface=authOriginValid&&(["LOGIN_FLOW","X_AUTH","CHALLENGE_FLOW","ACCOUNT_ACCESS"].includes(pathnameCategory)||(flow.authFlowActive&&flow.authFlowLineageValid&&flow.authFlowOrigin===url?.origin));const text=`${snapshot.title}\n${snapshot.visibleText}`;
    const textboxes=snapshot.controls.filter(control=>control.role==="textbox");const candidateIdentifiers=textboxes.filter(control=>control.type?.toLowerCase()!=="password"&&this.knownTextboxLabel(control.label)!=="UNKNOWN");const identifiers=textboxes.filter(control=>X_IDENTIFIER_LABELS.includes(control.label.trim() as typeof X_IDENTIFIER_LABELS[number])&&control.type?.toLowerCase()!=="password");const identifier=identifiers.length===1?identifiers[0]:undefined;
    const passwords=textboxes.filter(control=>control.type?.toLowerCase()==="password");const password=passwords.length===1?passwords[0]:undefined;const buttons=snapshot.controls.filter(control=>control.role==="button"),links=snapshot.controls.filter(control=>control.role==="link");const submit=this.identifierSubmitControl(snapshot);
    const formCountCategory=snapshot.formCountCategory??countCategory(snapshot.controls.some(control=>control.insideForm)?1:0);const activeFormPresent=authSurface&&formCountCategory!=="none";const activeFormUnambiguous=activeFormPresent&&formCountCategory==="one";
    const passwordTextboxPresent=authSurface&&passwords.length>0;const passwordVisible=password?.visible!==false;const passwordEnabled=!!password&&!password.disabled;const passwordFocusable=!!password&&password.focusable!==false;const passwordInsideActiveForm=!!password&&password.insideForm===true&&activeFormUnambiguous;const passwordAutocompleteCategory=this.passwordAutocompleteCategory(password?.autocomplete);const passwordPlausiblyLabeled=this.knownTextboxLabel(password?.label??"")==="PASSWORD";const submitSemanticKind=this.knownSubmitLabel(submit?.label);const submitVisible=!!submit&&this.controlVisible(snapshot,submit);const submitEnabled=!!submit&&!submit.disabled;const passwordActionable=authSurface&&passwords.length===1&&passwordVisible&&passwordEnabled&&passwordFocusable&&passwordInsideActiveForm&&passwordAutocompleteCategory!=="NEW_PASSWORD"&&passwordPlausiblyLabeled&&submitVisible&&submitEnabled&&submitSemanticKind!=="NONE"&&!candidateIdentifiers.some(control=>control.visible!==false&&control.disabled!==true);
    const continueControlPresent=authSurface&&!!submit;const usePasswordControlPresent=authSurface&&!!this.passwordAlternative(snapshot);const otpControls=authSurface?snapshot.controls.filter(control=>control.autocomplete?.toLowerCase()==="one-time-code"||X_VERIFICATION_LABELS.includes(control.label.trim() as typeof X_VERIFICATION_LABELS[number])):[];const verificationInputPresent=otpControls.length>0;const captchaWidgetPresent=authSurface&&X_CAPTCHA.test(text);const securityVerificationSurfacePresent=authSurface&&X_SECURITY_CHALLENGE.test(text);const emailVerification=authSurface&&X_EMAIL_CODE.test(text),smsVerification=authSurface&&X_SMS_CODE.test(text),mfaVerification=authSurface&&X_MFA.test(text);const mandatoryVerificationControlPresent=verificationInputPresent&&!usePasswordControlPresent;const authenticatedNavigationPresent=pathnameCategory==="AUTHENTICATED_APP";
    let surfaceKind:XAuthenticationSurfaceKind="UNKNOWN";if(authenticatedNavigationPresent)surfaceKind="AUTHENTICATED";else if(authSurface&&captchaWidgetPresent)surfaceKind="CAPTCHA";else if(authSurface&&securityVerificationSurfacePresent)surfaceKind="SECURITY_CHALLENGE";else if(authSurface&&X_LOGIN_FAILED.test(text))surfaceKind="LOGIN_FAILED";else if(authSurface&&passwordActionable)surfaceKind="PASSWORD_ENTRY";else if(authSurface&&passwordTextboxPresent&&!identifier)surfaceKind="AMBIGUOUS_PASSWORD_SURFACE";else if(authSurface&&(emailVerification||smsVerification||verificationInputPresent)&&usePasswordControlPresent)surfaceKind="VERIFICATION_WITH_PASSWORD_ALTERNATIVE";else if(authSurface&&emailVerification&&mandatoryVerificationControlPresent)surfaceKind="MANDATORY_EMAIL_CODE";else if(authSurface&&smsVerification&&mandatoryVerificationControlPresent)surfaceKind="MANDATORY_SMS_CODE";else if(authSurface&&mfaVerification&&mandatoryVerificationControlPresent)surfaceKind="MFA_REQUIRED";else if(authSurface&&identifier)surfaceKind=submit?"IDENTIFIER_ENTRY":"IDENTIFIER_ENTRY_READY";
    const identifierType=identifier?.type?.toLowerCase();const knownControlLabels=this.knownControlLabels(snapshot);return{surfaceKind,hostname:url?.hostname??"invalid",pathnameCategory,pathnamePattern,authOriginValid,...flow,identifierInjected,loginModalPresent:pathnameCategory==="LOGIN_FLOW",formPresent:formCountCategory!=="none",formCountCategory,activeFormPresent,activeFormUnambiguous,textboxCountCategory:countCategory(textboxes.length),identifierTextboxCountCategory:countCategory(candidateIdentifiers.length),passwordTextboxCountCategory:countCategory(passwords.length),identifierTextboxPresent:!!identifier,identifierTextboxRole:identifier?"textbox":"none",identifierTextboxType:identifierType==="text"||identifierType==="email"||identifierType==="tel"?identifierType:identifier?"other":"none",identifierTextboxVisible:identifier?.visible!==false,identifierTextboxEnabled:!!identifier&&!identifier.disabled,identifierTextboxFocusable:!!identifier&&identifier.focusable!==false,identifierTextboxInsideActiveForm:identifier?.insideForm===true&&activeFormUnambiguous,identifierTextboxInsideForm:identifier?.insideForm===true,identifierControlFocused:identifier?.focused===true,identifierControlHasAssociatedFormSubmit:identifier?.insideForm===true&&!!submit?.insideForm,passwordTextboxPresent,passwordTextboxVisible:passwordVisible,passwordTextboxEnabled:passwordEnabled,passwordTextboxFocusable:passwordFocusable,passwordTextboxInsideActiveForm:passwordInsideActiveForm,passwordAutocompleteCategory,knownIdentifierTextboxLabel:this.knownTextboxLabel(identifier?.label??""),knownPasswordTextboxLabel:this.knownTextboxLabel(password?.label??""),knownControlLabels,buttonCountCategory:countCategory(buttons.length),linkCountCategory:countCategory(links.length),submitControlPresent:!!submit,submitControlVisible:submitVisible,submitControlEnabled:submitEnabled,submitControlSemanticKind:submitSemanticKind,knownIdentifierSubmitLabel:submitSemanticKind,continueControlPresent,usePasswordControlPresent,verificationInputPresent,otpInputCountCategory:otpControls.length===0?"none":otpControls.length===1?"one":"multiple",captchaWidgetPresent,securityVerificationSurfacePresent,mandatoryVerificationControlPresent,authenticatedNavigationPresent};}
  classify(snapshot:AuthenticatedSiteSnapshot,flow:AuthenticationFlowObservation=INACTIVE_FLOW,identifierInjected=false):{step:XAuthenticationStep;passwordAlternative?:{role:"button"|"link";label:string}}{const fingerprint=this.fingerprint(snapshot,flow,identifierInjected);return{step:fingerprint.surfaceKind==="UNKNOWN"?"UNEXPECTED_AUTH_STATE":fingerprint.surfaceKind,passwordAlternative:fingerprint.surfaceKind==="VERIFICATION_WITH_PASSWORD_ALTERNATIVE"?this.passwordAlternative(snapshot):undefined};}
  detect(snapshot:AuthenticatedSiteSnapshot,flow:AuthenticationFlowObservation=INACTIVE_FLOW,identifierInjected=false):AuthenticatedSiteDetection{const {step}=this.classify(snapshot,flow,identifierInjected);if(step==="AUTHENTICATED")return{state:"ACTIVE",reason:"x_authenticated_surface"};if(step==="CAPTCHA"||step==="SECURITY_CHALLENGE")return{state:"CHALLENGE_REQUIRED",reason:step==="CAPTCHA"?"x_captcha":"x_security_challenge"};if(step==="MANDATORY_EMAIL_CODE")return{state:"MFA_REQUIRED",reason:"x_mandatory_email_code"};if(step==="MANDATORY_SMS_CODE")return{state:"MFA_REQUIRED",reason:"x_mandatory_sms_code"};if(step==="MFA_REQUIRED")return{state:"MFA_REQUIRED",reason:"x_mfa_required"};if(step==="LOGIN_FAILED")return{state:"REAUTH_REQUIRED",reason:"x_login_failed"};if(step==="IDENTIFIER_ENTRY"||step==="IDENTIFIER_ENTRY_READY"||step==="PASSWORD_ENTRY"||step==="VERIFICATION_WITH_PASSWORD_ALTERNATIVE")return{state:"REAUTH_REQUIRED",reason:`x_${step.toLowerCase()}`};return{state:"SESSION_EXPIRED",reason:"x_unexpected_auth_state"};}
  async bootstrap(browser:RuntimeAuthenticationBrowser,credential:CredentialMaterial,observer?:AuthenticatedBootstrapObserver,lineage?:AuthenticationFlowLineage,challenges?:AuthenticationChallengeRuntime):Promise<AuthenticatedSiteDetection>{
    let flow=lineage?await lineage.start():INACTIVE_FLOW;let identifierInjected=false;
    const inspect=async(snapshot:AuthenticatedSiteSnapshot)=>{flow=lineage?await lineage.observe(snapshot.url):INACTIVE_FLOW;return this.fingerprint(snapshot,flow,identifierInjected)};
    const classify=(snapshot:AuthenticatedSiteSnapshot)=>this.classify(snapshot,flow,identifierInjected);
    const detect=(snapshot:AuthenticatedSiteSnapshot)=>this.detect(snapshot,flow,identifierInjected);
    await observer?.stage("navigation_started");await at("navigation_started","INITIAL_NAVIGATION_FAILED",()=>browser.goto(lineage?.entryPoint.url??this.authenticationEntryPoint.url,{waitUntil:"domcontentloaded"}));await observer?.stage("navigation_completed");
    let snapshot=await at("navigation_completed","AUTH_SURFACE_TIMEOUT",()=>browser.waitForAuthenticationSurface?.()??browser.snapshot());let fingerprint=await inspect(snapshot);await observer?.stage("auth_surface_observed",fingerprintMetadata(fingerprint));if(!fingerprint.authOriginValid)throw new AuthenticatedBootstrapError("UNEXPECTED_AUTH_ORIGIN","auth_surface_observed",fingerprintMetadata(fingerprint));let classified=atSync("auth_surface_observed","AUTH_STATE_CLASSIFICATION_FAILED",()=>classify(snapshot));
    if(classified.step==="CAPTCHA"||classified.step==="SECURITY_CHALLENGE"||classified.step==="MANDATORY_EMAIL_CODE"||classified.step==="MANDATORY_SMS_CODE"||classified.step==="MFA_REQUIRED"){const kind=challengeKind(classified.step);if(challenges){const coordinated=await challenges.coordinator.coordinate({...challenges.binding,kind,phase:"PRE_IDENTIFIER",validateFences:challenges.validateFences,signal:challenges.signal,reobserve:async()=>{snapshot=await browser.snapshot();fingerprint=await inspect(snapshot);classified=classify(snapshot);return{challengePresent:isChallengeStep(classified.step),surfaceKind:fingerprint.surfaceKind}}});await observer?.stage("auth_state_classified",{authState:classified.step,challengeKind:kind,challengeProviderKind:coordinated.record.providerKind,challengeResolutionState:coordinated.record.state,challengeResolutionOutcome:coordinated.record.resolutionOutcome,challengeAttemptNumber:coordinated.record.attemptNumber,...fingerprintMetadata(fingerprint)});if(coordinated.mayContinue&&!isChallengeStep(classified.step)){}else{lineage?.invalidate();return{...detect(snapshot),challengeKind:kind,challengePhase:"PRE_IDENTIFIER",challengeProviderOutcome:coordinated.record.state}}}else{lineage?.invalidate();await observer?.stage("auth_state_classified",{authState:classified.step,...fingerprintMetadata(fingerprint)});return detect(snapshot)}}
    if(classified.step!=="IDENTIFIER_ENTRY"&&classified.step!=="IDENTIFIER_ENTRY_READY")throw new AuthenticatedBootstrapError("UNRECOGNIZED_AUTH_SURFACE","auth_surface_observed",fingerprintMetadata(fingerprint));
    const identifier=this.textControl(snapshot,X_IDENTIFIER_LABELS,false);if(!identifier)throw new AuthenticatedBootstrapError("IDENTIFIER_CONTROL_MISSING","auth_surface_observed",fingerprintMetadata(fingerprint));await observer?.stage("identifier_surface_recognized",fingerprintMetadata(fingerprint));await observer?.stage("identifier_control_found");
    await at("identifier_control_found","IDENTIFIER_INJECTION_FAILED",()=>browser.fillControl(identifier,credential.username));identifierInjected=true;await observer?.stage("identifier_injected");snapshot=await at("identifier_injected","UNRECOGNIZED_AUTH_SURFACE",()=>browser.snapshot());fingerprint=await inspect(snapshot);await observer?.stage("identifier_post_injection_surface_observed",fingerprintMetadata(fingerprint));classified=atSync("identifier_post_injection_surface_observed","AUTH_STATE_CLASSIFICATION_FAILED",()=>classify(snapshot));if(classified.step!=="IDENTIFIER_ENTRY"&&classified.step!=="IDENTIFIER_ENTRY_READY"){if(isChallengeStep(classified.step)){const kind=challengeKind(classified.step);if(challenges){const coordinated=await challenges.coordinator.coordinate({...challenges.binding,kind,phase:"POST_IDENTIFIER",validateFences:challenges.validateFences,signal:challenges.signal,reobserve:async()=>{snapshot=await browser.snapshot();fingerprint=await inspect(snapshot);classified=classify(snapshot);return{challengePresent:isChallengeStep(classified.step),surfaceKind:fingerprint.surfaceKind}}});await observer?.stage("auth_state_classified",{authState:classified.step,challengeKind:kind,challengeProviderKind:coordinated.record.providerKind,challengeResolutionState:coordinated.record.state,challengeResolutionOutcome:coordinated.record.resolutionOutcome,challengeAttemptNumber:coordinated.record.attemptNumber,...fingerprintMetadata(fingerprint)});if(!coordinated.mayContinue||isChallengeStep(classified.step)){lineage?.invalidate();return{...detect(snapshot),challengeKind:kind,challengePhase:"POST_IDENTIFIER",challengeProviderOutcome:coordinated.record.state}}}else{lineage?.invalidate();await observer?.stage("auth_state_classified",{authState:classified.step,...fingerprintMetadata(fingerprint)});return detect(snapshot)}}throw new AuthenticatedBootstrapError("IDENTIFIER_SUBMISSION_CONTROL_MISSING","identifier_post_injection_surface_observed",fingerprintMetadata(fingerprint))}const next=this.identifierSubmitControl(snapshot);if(!next||next.disabled)throw new AuthenticatedBootstrapError("IDENTIFIER_SUBMISSION_CONTROL_MISSING","identifier_post_injection_surface_observed",fingerprintMetadata(fingerprint));await observer?.stage("identifier_submit_control_detected",fingerprintMetadata(fingerprint));await at("identifier_submit_control_detected","IDENTIFIER_SUBMISSION_FAILED",()=>browser.clickControl(next));await observer?.stage("identifier_submitted");snapshot=await at("identifier_submitted","UNRECOGNIZED_AUTH_SURFACE",()=>browser.snapshot());fingerprint=await inspect(snapshot);classified=atSync("identifier_submitted","AUTH_STATE_CLASSIFICATION_FAILED",()=>classify(snapshot));
    if(isChallengeStep(classified.step)){const kind=challengeKind(classified.step);if(challenges){const coordinated=await challenges.coordinator.coordinate({...challenges.binding,kind,phase:"PRE_PASSWORD",validateFences:challenges.validateFences,signal:challenges.signal,reobserve:async()=>{snapshot=await browser.snapshot();fingerprint=await inspect(snapshot);classified=classify(snapshot);return{challengePresent:isChallengeStep(classified.step),surfaceKind:fingerprint.surfaceKind}}});await observer?.stage("auth_state_classified",{authState:classified.step,challengeKind:kind,challengeProviderKind:coordinated.record.providerKind,challengeResolutionState:coordinated.record.state,challengeResolutionOutcome:coordinated.record.resolutionOutcome,challengeAttemptNumber:coordinated.record.attemptNumber,...fingerprintMetadata(fingerprint)});if(!coordinated.mayContinue||isChallengeStep(classified.step)){lineage?.invalidate();return{...detect(snapshot),challengeKind:kind,challengePhase:"PRE_PASSWORD",challengeProviderOutcome:coordinated.record.state}}}else{lineage?.invalidate();await observer?.stage("auth_state_classified",{authState:classified.step,...fingerprintMetadata(fingerprint)});return detect(snapshot)}}
    if(classified.step==="VERIFICATION_WITH_PASSWORD_ALTERNATIVE"){await observer?.stage("verification_surface_observed",fingerprintMetadata(fingerprint));await observer?.stage("password_alternative_detected");await at("password_alternative_detected","PASSWORD_ALTERNATIVE_SELECTION_FAILED",()=>browser.clickControl(classified.passwordAlternative!));await observer?.stage("password_alternative_selected");snapshot=await at("password_alternative_selected","PASSWORD_ROUTE_TRANSITION_FAILED",async()=>{await browser.waitForPasswordSurface?.();return browser.snapshot()});fingerprint=await inspect(snapshot);classified=atSync("password_alternative_selected","AUTH_STATE_CLASSIFICATION_FAILED",()=>classify(snapshot));if(classified.step!=="PASSWORD_ENTRY")throw new AuthenticatedBootstrapError("PASSWORD_ROUTE_TRANSITION_FAILED","password_alternative_selected",fingerprintMetadata(fingerprint));await observer?.stage("password_surface_observed",fingerprintMetadata(fingerprint));}
    if(classified.step!=="PASSWORD_ENTRY"){if(classified.step==="UNEXPECTED_AUTH_STATE")throw new AuthenticatedBootstrapError("UNRECOGNIZED_AUTH_SURFACE","identifier_submitted",fingerprintMetadata(fingerprint));if(classified.step==="AMBIGUOUS_PASSWORD_SURFACE")throw new AuthenticatedBootstrapError("PASSWORD_CONTROL_MISSING","identifier_submitted",fingerprintMetadata(fingerprint));lineage?.invalidate();await observer?.stage("auth_state_classified",{authState:classified.step,...fingerprintMetadata(fingerprint)});return detect(snapshot)}const password=this.textControl(snapshot,["Password"],true);const login=this.control(snapshot,["Continue","Log in","Sign in"],["button"]);if(!password||!login)throw new AuthenticatedBootstrapError("PASSWORD_CONTROL_MISSING","identifier_submitted",fingerprintMetadata(fingerprint));await observer?.stage("password_control_found");
    await at("password_control_found","PASSWORD_INJECTION_FAILED",()=>browser.fillControl(password,credential.password));await observer?.stage("password_injected");await at("password_injected","PASSWORD_SUBMISSION_FAILED",()=>browser.clickControl(login));await observer?.stage("password_submitted");snapshot=await at("password_submitted","UNRECOGNIZED_AUTH_SURFACE",()=>browser.snapshot());fingerprint=await inspect(snapshot);classified=atSync("password_submitted","AUTH_STATE_CLASSIFICATION_FAILED",()=>classify(snapshot));if(classified.step==="UNEXPECTED_AUTH_STATE")throw new AuthenticatedBootstrapError("UNRECOGNIZED_AUTH_SURFACE","password_submitted",fingerprintMetadata(fingerprint));lineage?.invalidate();await observer?.stage("auth_state_classified",{authState:classified.step,...fingerprintMetadata(fingerprint)});return detect(snapshot);}
  private passwordAlternative(snapshot:AuthenticatedSiteSnapshot){return this.control(snapshot,X_DIRECT_PASSWORD_LABELS,["button","link"])}
  private pathnameCategory(url:URL|undefined,trusted:boolean):XAuthenticationPathCategory{if(!url)return"INVALID";if(!trusted)return"FOREIGN";if(/^\/i\/flow\/login(?:\/|$)/.test(url.pathname))return"LOGIN_FLOW";if(/^\/(?:login)?$/.test(url.pathname))return"X_AUTH";if(/^\/i\/flow\/challenge(?:\/|$)/.test(url.pathname))return"CHALLENGE_FLOW";if(/^\/account\/access(?:\/|$)/.test(url.pathname))return"ACCOUNT_ACCESS";if(/^\/(?:home|explore|notifications)(?:\/|$)/.test(url.pathname)||/^\/[^/]+\/status\//.test(url.pathname))return"AUTHENTICATED_APP";return"OTHER_X";}
  private pathnamePattern(url:URL|undefined,trusted:boolean){if(!url)return"<invalid>";if(!trusted)return"<foreign>";const raw=url.pathname.split("/").filter(Boolean),segments=raw.slice(0,4).map(safePathSegment);return segments.length===0?"/":`/${segments.join("/")}${raw.length>4?"/<redacted>":""}`;}
  private identifierSubmitControl(snapshot:AuthenticatedSiteSnapshot){const known=this.control(snapshot,X_CONTINUE_LABELS,["button","link"]);if(known)return{...known,insideForm:snapshot.controls.find(c=>c.role===known.role&&c.label.trim()===known.label)?.insideForm,disabled:snapshot.controls.find(c=>c.role===known.role&&c.label.trim()===known.label)?.disabled};const submits=snapshot.controls.filter(c=>c.role==="button"&&c.type?.toLowerCase()==="submit"&&c.insideForm===true);return submits.length===1?{role:"button" as const,label:submits[0].label.trim(),insideForm:true,disabled:submits[0].disabled}:undefined;}
  private knownSubmitLabel(label:string|undefined):XAuthenticationSurfaceFingerprint["knownIdentifierSubmitLabel"]{if(label==="Continue")return"CONTINUE";if(label==="Next")return"NEXT";if(label==="Log in")return"LOGIN";if(label==="Sign in")return"SIGN_IN";return"NONE";}
  private knownTextboxLabel(label:string):KnownTextboxLabel{const normalized=label.trim().toLowerCase();if(normalized==="email")return"EMAIL";if(normalized==="username")return"USERNAME";if(["email or username","phone, email, or username"].includes(normalized))return"EMAIL_OR_USERNAME";if(normalized==="identifier")return"IDENTIFIER";if(normalized==="password")return"PASSWORD";if(["verification code","code","enter code","authentication code"].includes(normalized))return"VERIFICATION_CODE";return"UNKNOWN";}
  private knownControlLabels(snapshot:AuthenticatedSiteSnapshot):KnownControlLabel[]{const labels=new Set<KnownControlLabel>();for(const control of snapshot.controls){const normalized=control.label.trim().toLowerCase();if(normalized==="continue")labels.add("CONTINUE");else if(normalized==="next")labels.add("NEXT");else if(normalized==="login")labels.add("LOGIN");else if(normalized==="log in")labels.add("LOG_IN");else if(normalized==="sign in")labels.add("SIGN_IN");else if(X_DIRECT_PASSWORD_LABELS.some(label=>label.toLowerCase()===normalized))labels.add("USE_PASSWORD");else if(normalized==="forgot password")labels.add("FORGOT_PASSWORD");else if(normalized==="cancel")labels.add("CANCEL");else if(["create account","sign up"].includes(normalized))labels.add("OTHER_KNOWN_AUTH");}return [...labels].sort();}
  private passwordAutocompleteCategory(value:string|undefined):XAuthenticationSurfaceFingerprint["passwordAutocompleteCategory"]{const normalized=value?.trim().toLowerCase();if(normalized==="current-password")return"CURRENT_PASSWORD";if(normalized==="new-password")return"NEW_PASSWORD";return normalized?"OTHER":"NONE";}
  private controlVisible(snapshot:AuthenticatedSiteSnapshot,control:{role:"button"|"link";label:string}){const matches=snapshot.controls.filter(candidate=>candidate.role===control.role&&candidate.label.trim()===control.label.trim());return matches.length===1&&matches[0].visible!==false;}
  private textControl(snapshot:AuthenticatedSiteSnapshot,labels:readonly string[],password:boolean){const matches=snapshot.controls.filter(control=>control.role==="textbox"&&labels.includes(control.label.trim())&&(control.type?.toLowerCase()==="password")===password);return matches.length===1?{role:"textbox" as const,label:matches[0].label.trim()}:undefined;}
  private control(snapshot:AuthenticatedSiteSnapshot,labels:readonly string[],roles:readonly ("button"|"link")[]){const matches=snapshot.controls.filter(control=>roles.includes(control.role as "button"|"link")&&labels.includes(control.label.trim()));return matches.length===1?{role:matches[0].role as "button"|"link",label:matches[0].label.trim()}:undefined;}
}
export const AUTHENTICATED_READ_ONLY_DENIED_ACTIONS=["post","reply","like","repost","follow","unfollow","direct_message","delete","settings","purchase","subscribe"] as const;
export function assertAuthenticatedReadOnlyAction(action:string){if(AUTHENTICATED_READ_ONLY_DENIED_ACTIONS.includes(action as typeof AUTHENTICATED_READ_ONLY_DENIED_ACTIONS[number]))throw new Error("authenticated profile is read-only");if(!["navigate","inspect","extract","scroll","follow_content_link"].includes(action))throw new Error("authenticated action is not allowlisted");}

export interface AuthenticatedBrowserExecutorPort extends BrowserExecutorPort,StructuredBrowserUsePort{
  exportAuthenticatedSession(scope:BrowserScope):Promise<BrowserSessionState>;
  attachAuthenticatedSession(scope:BrowserScope,state:BrowserSessionState):Promise<void>;
  detectAuthenticatedState(scope:BrowserScope,adapter:AuthenticatedSiteAdapter):Promise<AuthenticatedSiteDetection>;
  establishAuthenticatedSession(scope:BrowserScope,adapter:AuthenticatedSiteAdapter,credential:CredentialMaterial,observer?:AuthenticatedBootstrapObserver,lineage?:AuthenticationFlowLineage,challenges?:AuthenticationChallengeRuntime):Promise<AuthenticatedSiteDetection>;
}
export class AuthenticatedBrowserLifecycle{
  constructor(private readonly repository:AuthenticatedProfileRepository,private readonly profiles:AuthenticatedProfileService,private readonly browser:AuthenticatedBrowserExecutorPort,private readonly adapters:Map<string,AuthenticatedSiteAdapter>){}
  async attach(input:{capability:AuthenticatedProfileCapability;scope:BrowserScope;ownerId:string;observer?:AuthenticatedBootstrapObserver;challengeCoordinator?:ChallengeCoordinator;bootstrapRequestId?:string;signal?:AbortSignal}){
    const profile=await this.repository.getSiteProfile(input.capability.profileId);if(!profile)throw new Error("authenticated profile unavailable");await this.profiles.assertActiveOwner(profile);const adapter=this.adapters.get(profile.siteFamily);if(!adapter)throw new Error("authenticated site adapter unavailable");assertCapabilityUsable(input.capability,profile,{tenantId:input.scope.tenantId,ownerId:input.ownerId,runId:input.scope.runId,browserGeneration:input.scope.generation,origin:adapter.loginOrigin});
    const saved=await this.profiles.loadSession(profile);if(saved){await this.browser.attachAuthenticatedSession(input.scope,saved);await this.browser.navigate(input.scope,adapter.loginOrigin==="https://x.com"?"https://x.com/home":adapter.loginOrigin);const detection=await this.browser.detectAuthenticatedState(input.scope,adapter);if(detection.state==="ACTIVE")return{profile,sessionReused:true,detection};await this.profiles.transition(profile,detection.state,{runId:input.scope.runId,reason:detection.reason});if(detection.state==="MFA_REQUIRED"||detection.state==="CHALLENGE_REQUIRED")return{profile,sessionReused:true,detection};}
    const lineage=adapter.authenticationEntryPoint?new RuntimeAuthenticationFlowLineage(adapter.authenticationEntryPoint,{tenantId:input.scope.tenantId,ownerId:input.ownerId,profileId:profile.id,profileVersion:profile.version,requestId:input.scope.runId,browserGeneration:input.scope.generation,browserContextId:input.scope.contextId,allowedOrigins:input.capability.allowedOrigins,expiresAt:input.capability.expiresAt},async()=>{const current=await this.repository.getSiteProfile(profile.id);if(!current||current.version!==profile.version)return false;try{assertCapabilityUsable(input.capability,current,{tenantId:input.scope.tenantId,ownerId:input.ownerId,runId:input.scope.runId,browserGeneration:input.scope.generation,origin:adapter.authenticationEntryPoint!.url});return true}catch{return false}}):undefined;
    const challenges=input.challengeCoordinator?{coordinator:input.challengeCoordinator,binding:{runId:input.scope.runId,bootstrapRequestId:input.bootstrapRequestId??input.scope.runId,tenantId:input.scope.tenantId,ownerId:input.ownerId,profileId:profile.id,profileVersion:profile.version,browserGeneration:input.scope.generation,authFlowId:makeId("auth_flow",input.scope.runId,profile.id,profile.version,input.scope.generation,input.scope.contextId),expiresAt:input.capability.expiresAt},validateFences:async()=>{const current=await this.repository.getSiteProfile(profile.id);if(!current)return false;try{assertCapabilityUsable(input.capability,current,{tenantId:input.scope.tenantId,ownerId:input.ownerId,runId:input.scope.runId,browserGeneration:input.scope.generation,origin:adapter.authenticationEntryPoint?.url??adapter.loginOrigin});return true}catch{return false}},signal:input.signal}:undefined;
    let credential:CredentialMaterial;try{credential=await this.profiles.loadCredential(profile)}catch(error){if(error instanceof AuthenticatedProfileError)throw new AuthenticatedBootstrapError(error.code==="AUTH_SECRET_DECRYPTION_FAILED"?"CREDENTIAL_DECRYPTION_FAILED":"CREDENTIAL_REFERENCE_MISSING","browser_context_initialized",{}, {cause:error});throw error}await input.observer?.stage("credential_retrieved");await input.observer?.stage("credential_decrypted");let detection:AuthenticatedSiteDetection;try{detection=await this.browser.establishAuthenticatedSession(input.scope,adapter,credential,input.observer,lineage,challenges)}finally{lineage?.invalidate();credential.username="";credential.password="";}
    if(detection.state!=="ACTIVE"){const reason=detection.challengeKind?`challenge:${detection.challengeKind}:${detection.challengePhase??"UNKNOWN"}:${detection.challengeProviderOutcome??"UNKNOWN"}`:detection.reason;const updated=await this.profiles.transition(profile,detection.state,{runId:input.scope.runId,reason});return{profile:updated,sessionReused:false,detection};}
    let session:BrowserSessionState;try{session=await this.browser.exportAuthenticatedSession(input.scope)}catch(error){throw new AuthenticatedBootstrapError("SESSION_CAPTURE_FAILED","auth_state_classified",{}, {cause:error})}await input.observer?.stage("session_captured");let updated;let encrypted=false;try{updated=await this.profiles.saveSession(profile,session,{runId:input.scope.runId,onEncrypted:async()=>{encrypted=true;await input.observer?.stage("session_encrypted")}})}catch(error){if(error instanceof AuthenticatedBootstrapError)throw error;throw new AuthenticatedBootstrapError(encrypted?"SESSION_PERSISTENCE_FAILED":"SESSION_ENCRYPTION_FAILED",encrypted?"session_encrypted":"session_captured",{}, {cause:error})}await input.observer?.stage("session_persisted");return{profile:updated,sessionReused:false,detection};
  }
}
async function at<T>(stage:AuthenticatedBootstrapStage,code:AuthenticatedBootstrapFailureCode,operation:()=>Promise<T>):Promise<T>{try{return await operation()}catch(error){if(error instanceof AuthenticatedBootstrapError)throw error;if(error instanceof BrowserNavigationError)throw new AuthenticatedBootstrapError(error.code,stage,{}, {cause:error});throw new AuthenticatedBootstrapError(code,stage,{}, {cause:error})}}
function atSync<T>(stage:AuthenticatedBootstrapStage,code:AuthenticatedBootstrapFailureCode,operation:()=>T):T{try{return operation()}catch(error){if(error instanceof AuthenticatedBootstrapError)throw error;throw new AuthenticatedBootstrapError(code,stage,{}, {cause:error})}}
function originMetadata(value:string):AuthenticatedBootstrapSafeMetadata{try{const url=new URL(value);return{actualOriginHost:url.hostname,expectedOrigin:"x.com"}}catch{return{expectedOrigin:"x.com"}}}
function fingerprintMetadata(value:XAuthenticationSurfaceFingerprint):AuthenticatedBootstrapSafeMetadata{return{surfaceKind:value.surfaceKind,hostname:value.hostname,pathnameCategory:value.pathnameCategory,pathnamePattern:value.pathnamePattern,authOriginValid:value.authOriginValid,authFlowActive:value.authFlowActive,authEntryPointKind:value.authEntryPointKind,authFlowOrigin:value.authFlowOrigin,sameOriginTransitionCount:value.sameOriginTransitionCount,authFlowLineageValid:value.authFlowLineageValid,identifierInjected:value.identifierInjected,loginModalPresent:value.loginModalPresent,formPresent:value.formPresent,formCountCategory:value.formCountCategory,activeFormPresent:value.activeFormPresent,activeFormUnambiguous:value.activeFormUnambiguous,textboxCountCategory:value.textboxCountCategory,identifierTextboxCountCategory:value.identifierTextboxCountCategory,passwordTextboxCountCategory:value.passwordTextboxCountCategory,identifierTextboxPresent:value.identifierTextboxPresent,identifierTextboxRole:value.identifierTextboxRole,identifierTextboxType:value.identifierTextboxType,identifierTextboxVisible:value.identifierTextboxVisible,identifierTextboxEnabled:value.identifierTextboxEnabled,identifierTextboxFocusable:value.identifierTextboxFocusable,identifierTextboxInsideActiveForm:value.identifierTextboxInsideActiveForm,identifierTextboxInsideForm:value.identifierTextboxInsideForm,identifierControlFocused:value.identifierControlFocused,identifierControlHasAssociatedFormSubmit:value.identifierControlHasAssociatedFormSubmit,passwordTextboxPresent:value.passwordTextboxPresent,passwordTextboxVisible:value.passwordTextboxVisible,passwordTextboxEnabled:value.passwordTextboxEnabled,passwordTextboxFocusable:value.passwordTextboxFocusable,passwordTextboxInsideActiveForm:value.passwordTextboxInsideActiveForm,passwordAutocompleteCategory:value.passwordAutocompleteCategory,knownIdentifierTextboxLabel:value.knownIdentifierTextboxLabel,knownPasswordTextboxLabel:value.knownPasswordTextboxLabel,knownControlLabels:value.knownControlLabels.join("|"),buttonCountCategory:value.buttonCountCategory,linkCountCategory:value.linkCountCategory,submitControlPresent:value.submitControlPresent,submitControlVisible:value.submitControlVisible,submitControlEnabled:value.submitControlEnabled,submitControlSemanticKind:value.submitControlSemanticKind,knownIdentifierSubmitLabel:value.knownIdentifierSubmitLabel,continueControlPresent:value.continueControlPresent,usePasswordControlPresent:value.usePasswordControlPresent,verificationInputPresent:value.verificationInputPresent,otpInputCountCategory:value.otpInputCountCategory,captchaWidgetPresent:value.captchaWidgetPresent,securityVerificationSurfacePresent:value.securityVerificationSurfacePresent,mandatoryVerificationControlPresent:value.mandatoryVerificationControlPresent,authenticatedNavigationPresent:value.authenticatedNavigationPresent}}
function countCategory(value:number):CountCategory{return value===0?"none":value===1?"one":value<=3?"few":"many"}
function isChallengeStep(step:XAuthenticationStep){return step==="CAPTCHA"||step==="SECURITY_CHALLENGE"||step==="MANDATORY_EMAIL_CODE"||step==="MANDATORY_SMS_CODE"||step==="MFA_REQUIRED"}
function challengeKind(step:XAuthenticationStep):AuthenticationChallengeKind{if(step==="CAPTCHA")return"CAPTCHA";if(step==="SECURITY_CHALLENGE")return"SECURITY_CHALLENGE";if(step==="MANDATORY_EMAIL_CODE")return"EMAIL_VERIFICATION";if(step==="MFA_REQUIRED"||step==="MANDATORY_SMS_CODE")return"MFA";return"UNKNOWN"}
function safePathSegment(value:string){let decoded:string;try{decoded=decodeURIComponent(value)}catch{return"<opaque>"}const normalized=decoded.toLowerCase();if(X_SAFE_PATH_SEGMENTS.has(normalized))return normalized;if(/^[^/\s@]+@[^/\s@]+\.[^/\s@]+$/.test(decoded))return"<email>";if(/^\d{6,}$/.test(decoded)||/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(decoded))return"<id>";if(decoded.length>=12&&/[a-z]/i.test(decoded)&&/\d/.test(decoded))return"<opaque>";return"<redacted>"}
