import { AuthenticatedProfileError,assertCapabilityUsable,type AuthenticatedProfileCapability,type AuthenticatedProfileRepository,type AuthenticatedSessionState,type AuthenticatedProfileService,type BrowserSessionState,type CredentialMaterial } from "./auth-profile";
import { BrowserNavigationError,type BrowserExecutorPort,type BrowserScope,type StructuredBrowserUsePort } from "./browser";
export type AuthenticatedSiteDetection={state:AuthenticatedSessionState;reason:string};
export type AuthenticatedBootstrapStage="profile_resolved"|"browser_allocated"|"browser_context_initialized"|"credential_retrieved"|"credential_decrypted"|"navigation_started"|"navigation_completed"|"auth_surface_observed"|"identifier_control_found"|"identifier_injected"|"identifier_submitted"|"verification_surface_observed"|"password_alternative_detected"|"password_alternative_selected"|"password_surface_observed"|"password_control_found"|"password_injected"|"password_submitted"|"auth_state_classified"|"session_captured"|"session_encrypted"|"session_persisted";
export type AuthenticatedBootstrapFailureCode="CREDENTIAL_REFERENCE_MISSING"|"CREDENTIAL_DECRYPTION_FAILED"|"BROWSER_ALLOCATION_FAILED"|"BROWSER_CONTEXT_INITIALIZATION_FAILED"|"INITIAL_NAVIGATION_FAILED"|"NAVIGATION_TIMEOUT"|"UNEXPECTED_AUTH_ORIGIN"|"NETWORK_POLICY_DENIED"|"AUTH_SURFACE_NOT_RECOGNIZED"|"IDENTIFIER_CONTROL_MISSING"|"IDENTIFIER_INJECTION_FAILED"|"IDENTIFIER_SUBMISSION_FAILED"|"PASSWORD_ALTERNATIVE_CONTROL_MISSING"|"PASSWORD_ALTERNATIVE_SELECTION_FAILED"|"PASSWORD_ROUTE_TRANSITION_FAILED"|"PASSWORD_CONTROL_MISSING"|"PASSWORD_INJECTION_FAILED"|"PASSWORD_SUBMISSION_FAILED"|"AUTH_STATE_CLASSIFICATION_FAILED"|"SESSION_CAPTURE_FAILED"|"SESSION_ENCRYPTION_FAILED"|"SESSION_PERSISTENCE_FAILED"|"BOOTSTRAP_INFRASTRUCTURE_FAILED";
export type AuthenticatedBootstrapSafeMetadata=Record<string,string|number|boolean|undefined>;
export interface AuthenticatedBootstrapObserver{stage(stage:AuthenticatedBootstrapStage,metadata?:AuthenticatedBootstrapSafeMetadata):Promise<void>}
export class AuthenticatedBootstrapError extends Error{constructor(public readonly code:AuthenticatedBootstrapFailureCode,public readonly stage:AuthenticatedBootstrapStage,public readonly safeMetadata:AuthenticatedBootstrapSafeMetadata={},options?:{cause?:unknown}){super(code,options);this.name="AuthenticatedBootstrapError";}}
export interface AuthenticatedSiteSnapshot{url:string;title:string;visibleText:string;controls:Array<{role?:string;label:string;type?:string}>}
export interface RuntimeAuthenticationBrowser{goto(url:string,options?:{waitUntil?:"networkidle"|"domcontentloaded"}):Promise<void>;fill(selector:string,value:string):Promise<void>;fillControl(control:{role:"textbox";label:string},value:string):Promise<void>;click(selector:string):Promise<void>;clickControl(control:{role:"button"|"link";label:string}):Promise<void>;waitForPasswordSurface?():Promise<void>;snapshot():Promise<AuthenticatedSiteSnapshot>;importSession(state:BrowserSessionState):Promise<void>;exportSession():Promise<BrowserSessionState>}
export interface AuthenticatedSiteAdapter{readonly siteFamily:string;readonly allowedOrigins:readonly string[];readonly authenticationNetworkOrigins?:readonly string[];readonly authenticationWriteOrigins?:readonly string[];readonly loginOrigin:string;detect(snapshot:AuthenticatedSiteSnapshot):AuthenticatedSiteDetection;bootstrap(browser:RuntimeAuthenticationBrowser,credential:CredentialMaterial,observer?:AuthenticatedBootstrapObserver):Promise<AuthenticatedSiteDetection>}
export type XAuthenticationStep="IDENTIFIER_ENTRY"|"PASSWORD_ENTRY"|"VERIFICATION_WITH_PASSWORD_ALTERNATIVE"|"MANDATORY_EMAIL_CODE"|"MANDATORY_SMS_CODE"|"MFA_REQUIRED"|"SECURITY_CHALLENGE"|"CAPTCHA"|"AUTHENTICATED"|"LOGIN_FAILED"|"UNEXPECTED_AUTH_STATE";
const X_SECURITY_CHALLENGE=/arkose|security key|unusual activity|suspicious login|verify (?:that )?you(?:'|’)re human/i;const X_CAPTCHA=/captcha/i;const X_EMAIL_CODE=/check your email|code (?:we )?sent to (?:your )?email|email verification code/i;const X_SMS_CODE=/check your phone|code (?:we )?sent (?:to your phone|by (?:text|sms))|sms code/i;const X_MFA=/two-factor|authentication code|authenticator app/i;const X_LOGIN_FAILED=/incorrect password|wrong password|could not log you in|login failed/i;const X_LOGIN=/log in to x|sign in to x|enter your phone, email, or username/i;
const X_DIRECT_PASSWORD_LABELS=["Use password","Use password instead","Log in with password"] as const;
export class XAuthenticatedSiteAdapter implements AuthenticatedSiteAdapter{
  readonly siteFamily="x";readonly allowedOrigins=["https://x.com","https://twitter.com"] as const;readonly loginOrigin="https://x.com";
  readonly authenticationNetworkOrigins=[...this.allowedOrigins,"https://api.x.com","https://api.twitter.com","https://abs.twimg.com","https://pbs.twimg.com","https://ton.twimg.com","https://video.twimg.com","https://syndication.twitter.com"] as const;
  readonly authenticationWriteOrigins=["https://x.com","https://twitter.com","https://api.x.com","https://api.twitter.com"] as const;
  classify(snapshot:AuthenticatedSiteSnapshot):{step:XAuthenticationStep;passwordAlternative?:{role:"button"|"link";label:string}}{const text=`${snapshot.title}\n${snapshot.visibleText}`;const url=new URL(snapshot.url);const trustedOrigin=this.allowedOrigins.includes(url.origin as typeof this.allowedOrigins[number]);const authSurface=trustedOrigin&&(/\/i\/flow\/(?:login|challenge)/.test(url.pathname)||/\/account\/access/.test(url.pathname));if(!trustedOrigin)return{step:"SECURITY_CHALLENGE"};if(/\/home|\/explore|\/notifications|\/[^/]+\/status\//.test(url.pathname))return{step:"AUTHENTICATED"};if(authSurface&&snapshot.controls.some(control=>control.type?.toLowerCase()==="password"))return{step:"PASSWORD_ENTRY"};if(X_CAPTCHA.test(text))return{step:"CAPTCHA"};if(X_SECURITY_CHALLENGE.test(text))return{step:"SECURITY_CHALLENGE"};if(X_LOGIN_FAILED.test(text))return{step:"LOGIN_FAILED"};const passwordAlternative=authSurface?this.passwordAlternative(snapshot):undefined;if(authSurface&&(X_EMAIL_CODE.test(text)||X_SMS_CODE.test(text)||/verification code|enter the code/i.test(text))&&passwordAlternative)return{step:"VERIFICATION_WITH_PASSWORD_ALTERNATIVE",passwordAlternative};if(X_EMAIL_CODE.test(text))return{step:"MANDATORY_EMAIL_CODE"};if(X_SMS_CODE.test(text))return{step:"MANDATORY_SMS_CODE"};if(X_MFA.test(text)||/\/i\/flow\/challenge/.test(url.pathname))return{step:"MFA_REQUIRED"};if(/\/account\/access/.test(url.pathname))return{step:"SECURITY_CHALLENGE"};if(authSurface&&(X_LOGIN.test(text)||snapshot.controls.some(control=>control.role==="textbox"&&control.type?.toLowerCase()!=="password")))return{step:"IDENTIFIER_ENTRY"};return{step:"UNEXPECTED_AUTH_STATE"};}
  detect(snapshot:AuthenticatedSiteSnapshot):AuthenticatedSiteDetection{const {step}=this.classify(snapshot);if(step==="AUTHENTICATED")return{state:"ACTIVE",reason:"x_authenticated_surface"};if(step==="CAPTCHA"||step==="SECURITY_CHALLENGE")return{state:"CHALLENGE_REQUIRED",reason:step==="CAPTCHA"?"x_captcha":"x_security_challenge"};if(step==="MANDATORY_EMAIL_CODE")return{state:"MFA_REQUIRED",reason:"x_mandatory_email_code"};if(step==="MANDATORY_SMS_CODE")return{state:"MFA_REQUIRED",reason:"x_mandatory_sms_code"};if(step==="MFA_REQUIRED")return{state:"MFA_REQUIRED",reason:"x_mfa_required"};if(step==="LOGIN_FAILED")return{state:"REAUTH_REQUIRED",reason:"x_login_failed"};if(step==="IDENTIFIER_ENTRY"||step==="PASSWORD_ENTRY"||step==="VERIFICATION_WITH_PASSWORD_ALTERNATIVE")return{state:"REAUTH_REQUIRED",reason:`x_${step.toLowerCase()}`};return{state:"SESSION_EXPIRED",reason:"x_unexpected_auth_state"};}
  async bootstrap(browser:RuntimeAuthenticationBrowser,credential:CredentialMaterial,observer?:AuthenticatedBootstrapObserver):Promise<AuthenticatedSiteDetection>{
    await observer?.stage("navigation_started");await at("navigation_started","INITIAL_NAVIGATION_FAILED",()=>browser.goto("https://x.com/i/flow/login",{waitUntil:"domcontentloaded"}));await observer?.stage("navigation_completed");
    let snapshot=await at("navigation_completed","AUTH_SURFACE_NOT_RECOGNIZED",()=>browser.snapshot());await observer?.stage("auth_surface_observed",originMetadata(snapshot.url));let classified=atSync("auth_surface_observed","AUTH_STATE_CLASSIFICATION_FAILED",()=>this.classify(snapshot));
    if(classified.step==="CAPTCHA"||classified.step==="SECURITY_CHALLENGE"||classified.step==="MANDATORY_EMAIL_CODE"||classified.step==="MANDATORY_SMS_CODE"||classified.step==="MFA_REQUIRED"){await observer?.stage("auth_state_classified",{authState:classified.step});return this.detect(snapshot)}
    if(classified.step!=="IDENTIFIER_ENTRY")throw new AuthenticatedBootstrapError("AUTH_SURFACE_NOT_RECOGNIZED","auth_surface_observed",{authState:classified.step,...originMetadata(snapshot.url)});
    const identifier=this.textControl(snapshot,["Email or username","Phone, email, or username"],false);const next=this.control(snapshot,["Continue","Next"],["button"]);if(!identifier||!next)throw new AuthenticatedBootstrapError("IDENTIFIER_CONTROL_MISSING","auth_surface_observed",originMetadata(snapshot.url));await observer?.stage("identifier_control_found");
    await at("identifier_control_found","IDENTIFIER_INJECTION_FAILED",()=>browser.fillControl(identifier,credential.username));await observer?.stage("identifier_injected");await at("identifier_injected","IDENTIFIER_SUBMISSION_FAILED",()=>browser.clickControl(next));await observer?.stage("identifier_submitted");snapshot=await at("identifier_submitted","AUTH_SURFACE_NOT_RECOGNIZED",()=>browser.snapshot());classified=atSync("identifier_submitted","AUTH_STATE_CLASSIFICATION_FAILED",()=>this.classify(snapshot));
    if(classified.step==="VERIFICATION_WITH_PASSWORD_ALTERNATIVE"){await observer?.stage("verification_surface_observed",originMetadata(snapshot.url));await observer?.stage("password_alternative_detected");await at("password_alternative_detected","PASSWORD_ALTERNATIVE_SELECTION_FAILED",()=>browser.clickControl(classified.passwordAlternative!));await observer?.stage("password_alternative_selected");snapshot=await at("password_alternative_selected","PASSWORD_ROUTE_TRANSITION_FAILED",async()=>{await browser.waitForPasswordSurface?.();return browser.snapshot()});classified=atSync("password_alternative_selected","AUTH_STATE_CLASSIFICATION_FAILED",()=>this.classify(snapshot));if(classified.step!=="PASSWORD_ENTRY")throw new AuthenticatedBootstrapError("PASSWORD_ROUTE_TRANSITION_FAILED","password_alternative_selected",originMetadata(snapshot.url));await observer?.stage("password_surface_observed",originMetadata(snapshot.url));}
    if(classified.step!=="PASSWORD_ENTRY"){if(classified.step==="UNEXPECTED_AUTH_STATE")throw new AuthenticatedBootstrapError("AUTH_STATE_CLASSIFICATION_FAILED","identifier_submitted",originMetadata(snapshot.url));await observer?.stage("auth_state_classified",{authState:classified.step});return this.detect(snapshot)}const password=this.textControl(snapshot,["Password"],true);const login=this.control(snapshot,["Continue","Log in","Sign in"],["button"]);if(!password||!login)throw new AuthenticatedBootstrapError("PASSWORD_CONTROL_MISSING","identifier_submitted",originMetadata(snapshot.url));await observer?.stage("password_control_found");
    await at("password_control_found","PASSWORD_INJECTION_FAILED",()=>browser.fillControl(password,credential.password));await observer?.stage("password_injected");await at("password_injected","PASSWORD_SUBMISSION_FAILED",()=>browser.clickControl(login));await observer?.stage("password_submitted");snapshot=await at("password_submitted","AUTH_SURFACE_NOT_RECOGNIZED",()=>browser.snapshot());classified=atSync("password_submitted","AUTH_STATE_CLASSIFICATION_FAILED",()=>this.classify(snapshot));if(classified.step==="UNEXPECTED_AUTH_STATE")throw new AuthenticatedBootstrapError("AUTH_STATE_CLASSIFICATION_FAILED","password_submitted",originMetadata(snapshot.url));await observer?.stage("auth_state_classified",{authState:classified.step});return this.detect(snapshot);}
  private passwordAlternative(snapshot:AuthenticatedSiteSnapshot){return this.control(snapshot,X_DIRECT_PASSWORD_LABELS,["button","link"])}
  private textControl(snapshot:AuthenticatedSiteSnapshot,labels:readonly string[],password:boolean){const matches=snapshot.controls.filter(control=>control.role==="textbox"&&labels.includes(control.label.trim())&&(control.type?.toLowerCase()==="password")===password);return matches.length===1?{role:"textbox" as const,label:matches[0].label.trim()}:undefined;}
  private control(snapshot:AuthenticatedSiteSnapshot,labels:readonly string[],roles:readonly ("button"|"link")[]){const matches=snapshot.controls.filter(control=>roles.includes(control.role as "button"|"link")&&labels.includes(control.label.trim()));return matches.length===1?{role:matches[0].role as "button"|"link",label:matches[0].label.trim()}:undefined;}
}
export const AUTHENTICATED_READ_ONLY_DENIED_ACTIONS=["post","reply","like","repost","follow","unfollow","direct_message","delete","settings","purchase","subscribe"] as const;
export function assertAuthenticatedReadOnlyAction(action:string){if(AUTHENTICATED_READ_ONLY_DENIED_ACTIONS.includes(action as typeof AUTHENTICATED_READ_ONLY_DENIED_ACTIONS[number]))throw new Error("authenticated profile is read-only");if(!["navigate","inspect","extract","scroll","follow_content_link"].includes(action))throw new Error("authenticated action is not allowlisted");}

export interface AuthenticatedBrowserExecutorPort extends BrowserExecutorPort,StructuredBrowserUsePort{
  exportAuthenticatedSession(scope:BrowserScope):Promise<BrowserSessionState>;
  attachAuthenticatedSession(scope:BrowserScope,state:BrowserSessionState):Promise<void>;
  detectAuthenticatedState(scope:BrowserScope,adapter:AuthenticatedSiteAdapter):Promise<AuthenticatedSiteDetection>;
  establishAuthenticatedSession(scope:BrowserScope,adapter:AuthenticatedSiteAdapter,credential:CredentialMaterial,observer?:AuthenticatedBootstrapObserver):Promise<AuthenticatedSiteDetection>;
}
export class AuthenticatedBrowserLifecycle{
  constructor(private readonly repository:AuthenticatedProfileRepository,private readonly profiles:AuthenticatedProfileService,private readonly browser:AuthenticatedBrowserExecutorPort,private readonly adapters:Map<string,AuthenticatedSiteAdapter>){}
  async attach(input:{capability:AuthenticatedProfileCapability;scope:BrowserScope;ownerId:string;observer?:AuthenticatedBootstrapObserver}){
    const profile=await this.repository.getSiteProfile(input.capability.profileId);if(!profile)throw new Error("authenticated profile unavailable");await this.profiles.assertActiveOwner(profile);const adapter=this.adapters.get(profile.siteFamily);if(!adapter)throw new Error("authenticated site adapter unavailable");assertCapabilityUsable(input.capability,profile,{tenantId:input.scope.tenantId,ownerId:input.ownerId,runId:input.scope.runId,browserGeneration:input.scope.generation,origin:adapter.loginOrigin});
    const saved=await this.profiles.loadSession(profile);if(saved){await this.browser.attachAuthenticatedSession(input.scope,saved);await this.browser.navigate(input.scope,adapter.loginOrigin==="https://x.com"?"https://x.com/home":adapter.loginOrigin);const detection=await this.browser.detectAuthenticatedState(input.scope,adapter);if(detection.state==="ACTIVE")return{profile,sessionReused:true,detection};await this.profiles.transition(profile,detection.state,{runId:input.scope.runId,reason:detection.reason});if(detection.state==="MFA_REQUIRED"||detection.state==="CHALLENGE_REQUIRED")return{profile,sessionReused:true,detection};}
    let credential:CredentialMaterial;try{credential=await this.profiles.loadCredential(profile)}catch(error){if(error instanceof AuthenticatedProfileError)throw new AuthenticatedBootstrapError(error.code==="AUTH_SECRET_DECRYPTION_FAILED"?"CREDENTIAL_DECRYPTION_FAILED":"CREDENTIAL_REFERENCE_MISSING","browser_context_initialized",{}, {cause:error});throw error}await input.observer?.stage("credential_retrieved");await input.observer?.stage("credential_decrypted");let detection:AuthenticatedSiteDetection;try{detection=await this.browser.establishAuthenticatedSession(input.scope,adapter,credential,input.observer)}finally{credential.username="";credential.password="";}
    if(detection.state!=="ACTIVE"){await this.profiles.transition(profile,detection.state,{runId:input.scope.runId,reason:detection.reason});return{profile,sessionReused:false,detection};}
    let session:BrowserSessionState;try{session=await this.browser.exportAuthenticatedSession(input.scope)}catch(error){throw new AuthenticatedBootstrapError("SESSION_CAPTURE_FAILED","auth_state_classified",{}, {cause:error})}await input.observer?.stage("session_captured");let updated;let encrypted=false;try{updated=await this.profiles.saveSession(profile,session,{runId:input.scope.runId,onEncrypted:async()=>{encrypted=true;await input.observer?.stage("session_encrypted")}})}catch(error){if(error instanceof AuthenticatedBootstrapError)throw error;throw new AuthenticatedBootstrapError(encrypted?"SESSION_PERSISTENCE_FAILED":"SESSION_ENCRYPTION_FAILED",encrypted?"session_encrypted":"session_captured",{}, {cause:error})}await input.observer?.stage("session_persisted");return{profile:updated,sessionReused:false,detection};
  }
}
async function at<T>(stage:AuthenticatedBootstrapStage,code:AuthenticatedBootstrapFailureCode,operation:()=>Promise<T>):Promise<T>{try{return await operation()}catch(error){if(error instanceof AuthenticatedBootstrapError)throw error;if(error instanceof BrowserNavigationError)throw new AuthenticatedBootstrapError(error.code,stage,{}, {cause:error});throw new AuthenticatedBootstrapError(code,stage,{}, {cause:error})}}
function atSync<T>(stage:AuthenticatedBootstrapStage,code:AuthenticatedBootstrapFailureCode,operation:()=>T):T{try{return operation()}catch(error){if(error instanceof AuthenticatedBootstrapError)throw error;throw new AuthenticatedBootstrapError(code,stage,{}, {cause:error})}}
function originMetadata(value:string):AuthenticatedBootstrapSafeMetadata{try{const url=new URL(value);return{actualOriginHost:url.hostname,expectedOrigin:"x.com"}}catch{return{expectedOrigin:"x.com"}}}
