#!/usr/bin/env node

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  environmentConfig,
  parseEnvFile,
  repositoryRoot,
  workerDirectory,
  readWorkerConfig,
  usableValue
} from "./lib/release-config.mjs";

const environment = optionValue("--environment") ?? "staging";
const envPath = resolve(repositoryRoot, ".env");
const examplePath = resolve(repositoryRoot, ".env.example");
const devVarsPath = resolve(workerDirectory, ".dev.vars");
const secretsPath = resolve(workerDirectory, `.secrets.${environment}.env`);
const generatedSecretKeys = [
  "ADMIN_SESSION_SECRET",
  "ADMIN_SETUP_TOKEN",
  "INTERNAL_MAINTENANCE_SECRET"
];
const workerSecretKeys = [
  ...generatedSecretKeys,
  "OPENAI_API_KEY",
  "CLOUDFLARE_AI_GATEWAY_TOKEN",
  "APIFY_API_TOKEN",
  "BRAVE_SEARCH_API_KEY",
  "TURNSTILE_SECRET_KEY"
];

if (!["staging", "production"].includes(environment)) {
  throw new Error("--environment must be staging or production.");
}

if (!existsSync(envPath)) {
  writeFileSync(envPath, existsSync(examplePath) ? readFileSync(examplePath, "utf8") : "", {
    mode: 0o600
  });
}

const values = parseEnvFile(envPath);
let envText = readFileSync(envPath, "utf8");
const generated = [];

for (const key of generatedSecretKeys) {
  if (usableValue(values.get(key))) continue;
  const value = randomBytes(32).toString("base64url");
  values.set(key, value);
  envText = setEnvValue(envText, key, value);
  generated.push(key);
}

writeFileSync(envPath, envText.replace(/\n*$/, "\n"), { mode: 0o600 });

const configVars = environmentConfig(readWorkerConfig(), environment).vars ?? {};
const devVars = [
  "# Generated by pnpm setup. Do not commit.",
  `# Local runtime defaults mirror the ${environment} Wrangler environment.`,
  ...Object.entries(configVars).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
  ...workerSecretKeys
    .filter((key) => usableValue(values.get(key)))
    .map((key) => `${key}=${formatEnvValue(values.get(key))}`)
];
writeFileSync(devVarsPath, `${devVars.join("\n")}\n`, { mode: 0o600 });
const deploySecrets = [
  "# Generated by pnpm setup. Do not commit.",
  ...workerSecretKeys
    .filter((key) => usableValue(values.get(key)))
    .map((key) => `${key}=${formatEnvValue(values.get(key))}`)
];
writeFileSync(secretsPath, `${deploySecrets.join("\n")}\n`, { mode: 0o600 });

console.log("Distilled.news local initialization complete");
console.log(`- environment: ${environment}`);
console.log(`- .env: ${existsSync(envPath) ? "ready" : "missing"}`);
console.log(`- apps/worker/.dev.vars: wrote ${workerSecretKeys.filter((key) => usableValue(values.get(key))).length} secrets`);
console.log(`- apps/worker/.secrets.${environment}.env: deploy-only secret file ready`);
console.log(`- generated secrets: ${generated.length > 0 ? generated.join(", ") : "none (existing values preserved)"}`);
console.log("\nNo Cloudflare resources, secrets, migrations, or deployments were changed.");
console.log(`Run "pnpm doctor -- --environment ${environment}" for the read-only readiness report.`);

function optionValue(name) {
  const direct = process.argv.slice(2).find((argument) => argument.startsWith(`${name}=`));
  if (direct) return direct.slice(name.length + 1);
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function setEnvValue(text, key, value) {
  const lines = text.split(/\r?\n/);
  const index = lines.findIndex((line) => line.trimStart().startsWith(`${key}=`));
  const replacement = `${key}=${formatEnvValue(value)}`;
  if (index >= 0) lines[index] = replacement;
  else lines.push(replacement);
  return lines.join("\n");
}

function formatEnvValue(value) {
  const text = String(value ?? "");
  return /[\s#"'`]/.test(text) ? JSON.stringify(text) : text;
}
