import { describe,expect,it } from "vitest";
import {
  AuthenticatedProfileService,ProfileEnvelopeCrypto,assertCapabilityUsable,issueAuthenticatedProfileCapability,
  projectAuthenticatedProfileForModel,type AuthAuditEvent,type AuthenticatedProfileRepository,type AuthenticatedSiteProfile,
  type AuthenticatedProfileOwnershipPolicy,type CredentialProfile,type SecretBlobStore
} from "../src/auth-profile";
import { AuthenticatedBrowserLifecycle,XAuthenticatedSiteAdapter,assertAuthenticatedReadOnlyAction } from "../src/authenticated-site";

const ROOT=Buffer.alloc(32,7).toString("base64");
class Blobs implements SecretBlobStore{values=new Map<string,Uint8Array>();async put(ref:string,value:Uint8Array){this.values.set(ref,value)}async get(ref:string){return this.values.get(ref)??null}async delete(ref:string){this.values.delete(ref)}}
class Repo implements AuthenticatedProfileRepository{credentials=new Map<string,CredentialProfile>();profiles=new Map<string,AuthenticatedSiteProfile>();audits:AuthAuditEvent[]=[];async createCredentialProfile(v:CredentialProfile){this.credentials.set(v.id,structuredClone(v))}async createSiteProfile(v:AuthenticatedSiteProfile){if(!this.profiles.has(v.id))this.profiles.set(v.id,structuredClone(v))}async getCredentialProfile(id:string){return structuredClone(this.credentials.get(id)??null)}async getSiteProfile(id:string){return structuredClone(this.profiles.get(id)??null)}async updateSiteProfile(v:AuthenticatedSiteProfile){this.profiles.set(v.id,structuredClone(v))}async appendAuthAudit(v:AuthAuditEvent){this.audits.push(structuredClone(v))}}
class Owners implements AuthenticatedProfileOwnershipPolicy{accounts=new Map([["account-a",{disabled:false}],["account-b",{disabled:false}]]);async assertActiveOwner(input:{tenantId:string;ownerId:string}){const account=this.accounts.get(input.ownerId);if(!account)throw new Error("AUTH_OWNER_NOT_FOUND");if(account.disabled)throw new Error("AUTH_OWNER_DISABLED");}}
const NOW=new Date("2026-09-16T00:00:00Z");
async function fixture(){const repository=new Repo();const blobs=new Blobs();const crypto=new ProfileEnvelopeCrypto({current:ROOT},"current");const owners=new Owners();const service=new AuthenticatedProfileService(repository,blobs,crypto,owners);const safe=await service.provision({tenantId:"account-a",ownerId:"account-a",siteFamily:"x",allowedOrigins:["https://x.com"],credential:{username:"secret-user@example.com",password:"correct horse battery staple"},now:NOW});const profile=(await repository.getSiteProfile(safe.authenticatedProfileId))!;return{repository,blobs,crypto,owners,service,safe,profile};}

describe("authenticated profile security",()=>{
  it("projects only opaque safe metadata and never returns credentials or blob references",async()=>{const f=await fixture();const output=JSON.stringify(f.safe);expect(output).not.toContain("secret-user");expect(output).not.toContain("correct horse");expect(output).not.toContain("credential.v1.enc");expect(projectAuthenticatedProfileForModel(f.profile)).toEqual(f.safe);expect(JSON.stringify(f.repository.audits)).not.toContain("correct horse");});
  it("encrypts credentials with an authenticated versioned envelope and tenant-bound context",async()=>{const f=await fixture();const bytes=[...f.blobs.values.values()][0];const persisted=new TextDecoder().decode(bytes);expect(persisted).not.toContain("correct horse");expect(JSON.parse(persisted)).toMatchObject({version:1,algorithm:"AES-256-GCM",keyId:"current"});const credential=await f.service.loadCredential(f.profile);expect(credential.password).toBe("correct horse battery staple");const ref=f.repository.credentials.get(f.profile.credentialProfileId!)!.encryptedCredentialRef;await expect(f.crypto.decrypt((await f.blobs.get(ref))!,{tenantId:"account-b",profileId:f.profile.credentialProfileId!,purpose:"credential"})).rejects.toMatchObject({code:"AUTH_SECRET_DECRYPTION_FAILED"});});
  it("rejects corrupted ciphertext without including secret values in the error",async()=>{const f=await fixture();const ref=f.repository.credentials.get(f.profile.credentialProfileId!)!.encryptedCredentialRef;const blob=(await f.blobs.get(ref))!;blob[blob.length-2]^=1;let message="";try{await f.service.loadCredential(f.profile)}catch(error){message=String(error)}expect(message).toContain("could not be decrypted");expect(message).not.toContain("correct horse");});
  it("binds capabilities to tenant, owner, run, generation, origin, version, expiry and revocation",async()=>{const f=await fixture();const cap=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:3,now:NOW,ttlMs:1000});const valid={tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:3,origin:"https://x.com",now:"2026-09-16T00:00:00.500Z"};expect(()=>assertCapabilityUsable(cap,f.profile,valid)).not.toThrow();expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,tenantId:"account-b"})).toThrow(/AUTH_TENANT_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,ownerId:"account-b"})).toThrow(/AUTH_OWNER_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,runId:"run-b"})).toThrow(/AUTH_RUN_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,browserGeneration:4})).toThrow(/AUTH_STALE_GENERATION/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,origin:"https://evil.example"})).toThrow(/AUTH_ORIGIN_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,now:"2026-09-16T00:00:02Z"})).toThrow(/AUTH_CAPABILITY_EXPIRED/);expect(()=>assertCapabilityUsable(cap,{...f.profile,version:2},valid)).toThrow(/AUTH_STALE_CAPABILITY/);expect(()=>assertCapabilityUsable(cap,{...f.profile,sessionState:"REVOKED",revokedAt:NOW.toISOString()},valid)).toThrow(/AUTH_PROFILE_REVOKED/);});
  it("persists and reuses encrypted browser state without loading credentials",async()=>{const f=await fixture();const state={cookies:[{name:"auth_token",value:"cookie-secret",domain:".x.com",path:"/",expires:2_000_000_000,httpOnly:true,secure:true,sameSite:"None" as const}],origins:[{origin:"https://x.com",localStorage:[{name:"session",value:"storage-secret"}]}]};const active=await f.service.saveSession(f.profile,state,{runId:"run-a",now:NOW});expect(active.sessionState).toBe("ACTIVE");expect(new TextDecoder().decode((await f.blobs.get(active.encryptedSessionRef!))!)).not.toContain("cookie-secret");await f.blobs.delete(f.repository.credentials.get(f.profile.credentialProfileId!)!.encryptedCredentialRef);await expect(f.service.loadSession(active)).resolves.toEqual(state);});
  it("durably records typed challenge, expiry and revocation transitions",async()=>{const f=await fixture();const mfa=await f.service.transition(f.profile,"MFA_REQUIRED",{runId:"run-a",reason:"x_human_verification",now:NOW});const expired=await f.service.transition(mfa,"SESSION_EXPIRED",{runId:"run-b",reason:"login_wall",now:NOW});const revoked=await f.service.transition(expired,"REVOKED",{now:NOW});expect(revoked).toMatchObject({sessionState:"REVOKED",version:4,revokedAt:NOW.toISOString()});expect(f.repository.audits.map(a=>a.toState)).toEqual(["REAUTH_REQUIRED","MFA_REQUIRED","SESSION_EXPIRED","REVOKED"]);});
  it("is retry-idempotent after encrypted credential persistence",async()=>{const f=await fixture();const again=await f.service.provision({tenantId:"account-a",ownerId:"account-a",siteFamily:"x",allowedOrigins:["https://x.com"],credential:{username:"replacement",password:"replacement-secret"},now:NOW});expect(again.authenticatedProfileId).toBe(f.profile.id);expect(f.repository.profiles.size).toBe(1);expect([...f.blobs.values.keys()].filter(key=>key.includes("credential"))).toHaveLength(1);});
  it("rejects tenant-owner mismatch, missing, disabled, and live-smoke owners before persistence",async()=>{const f=await fixture();const attempt=(tenantId:string,ownerId:string)=>f.service.provision({tenantId,ownerId,siteFamily:"x",allowedOrigins:["https://x.com"],credential:{username:"not-persisted",password:"not-persisted"},now:NOW});await expect(attempt("account-a","account-b")).rejects.toMatchObject({code:"AUTH_TENANT_OWNER_MISMATCH"});await expect(attempt("missing","missing")).rejects.toThrow(/AUTH_OWNER_NOT_FOUND/);await expect(attempt("live-smoke","live-smoke")).rejects.toThrow(/AUTH_OWNER_NOT_FOUND/);f.owners.accounts.get("account-b")!.disabled=true;await expect(attempt("account-b","account-b")).rejects.toThrow(/AUTH_OWNER_DISABLED/);expect(JSON.stringify([...f.blobs.values.values()])).not.toContain("not-persisted");});
});

describe("generic adapters and read-only policy",()=>{
  const x=new XAuthenticatedSiteAdapter();const snap=(url:string,visibleText:string)=>({url,title:"X",visibleText,controls:[]});
  it("classifies X authenticated, login, MFA, CAPTCHA and foreign-origin states",()=>{expect(x.detect(snap("https://x.com/home","For you Following"))).toMatchObject({state:"ACTIVE"});expect(x.detect(snap("https://x.com/i/flow/login","Log in to X"))).toMatchObject({state:"REAUTH_REQUIRED"});expect(x.detect(snap("https://x.com/i/flow/challenge","Enter the verification code"))).toMatchObject({state:"MFA_REQUIRED"});expect(x.detect(snap("https://x.com/account/access","Complete CAPTCHA"))).toMatchObject({state:"CHALLENGE_REQUIRED"});expect(x.detect(snap("https://evil.example/","X"))).toMatchObject({state:"CHALLENGE_REQUIRED"});});
  it("cannot perform state-changing authenticated operations",()=>{for(const action of ["post","reply","like","repost","follow","direct_message","settings","purchase"])expect(()=>assertAuthenticatedReadOnlyAction(action)).toThrow(/read-only/);for(const action of ["navigate","inspect","extract","scroll","follow_content_link"])expect(()=>assertAuthenticatedReadOnlyAction(action)).not.toThrow();});
  it("stops bootstrap before password injection when a human challenge is present",async()=>{const calls:string[]=[];const browser={goto:async()=>{calls.push("goto")},fill:async(_selector:string,value:string)=>{calls.push(`fill:${value}`)},click:async()=>{calls.push("click")},snapshot:async()=>snap("https://x.com/account/access","Complete CAPTCHA"),importSession:async()=>{},exportSession:async()=>({cookies:[],origins:[]})};await expect(x.bootstrap(browser,{username:"user-secret",password:"password-secret"})).resolves.toMatchObject({state:"CHALLENGE_REQUIRED"});expect(calls).toEqual(["goto"]);});
  it("reuses an active encrypted session without loading or injecting credentials",async()=>{const f=await fixture();const active=await f.service.saveSession(f.profile,{cookies:[],origins:[]},{runId:"seed",now:NOW});const calls:string[]=[];const browser=fakeBrowser(calls,"ACTIVE");const capability=issueAuthenticatedProfileCapability(active,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const lifecycle=new AuthenticatedBrowserLifecycle(f.repository,f.service,browser as never,new Map([["x",x]]));await expect(lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"})).resolves.toMatchObject({sessionReused:true,detection:{state:"ACTIVE"}});expect(calls).toEqual(["attach","navigate","detect"]);});
  it("bootstraps only when no valid session exists and persists the resulting state",async()=>{const f=await fixture();const calls:string[]=[];const browser=fakeBrowser(calls,"ACTIVE");const capability=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const lifecycle=new AuthenticatedBrowserLifecycle(f.repository,f.service,browser as never,new Map([["x",x]]));const result=await lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"});expect(result).toMatchObject({sessionReused:false,detection:{state:"ACTIVE"},profile:{sessionState:"ACTIVE"}});expect(calls).toEqual(["establish","export"]);});
  it("rejects use after the owning account is disabled or deleted",async()=>{const f=await fixture();const capability=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const lifecycle=new AuthenticatedBrowserLifecycle(f.repository,f.service,fakeBrowser([],"ACTIVE") as never,new Map([["x",x]]));f.owners.accounts.get("account-a")!.disabled=true;await expect(lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"})).rejects.toThrow(/AUTH_OWNER_DISABLED/);f.owners.accounts.delete("account-a");await expect(lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"})).rejects.toThrow(/AUTH_OWNER_NOT_FOUND/);});
});

function fakeBrowser(calls:string[],state:"ACTIVE"|"MFA_REQUIRED"){return{attachAuthenticatedSession:async()=>{calls.push("attach")},navigate:async()=>{calls.push("navigate")},detectAuthenticatedState:async()=>{calls.push("detect");return{state,reason:"fixture"}},establishAuthenticatedSession:async()=>{calls.push("establish");return{state,reason:"fixture"}},exportAuthenticatedSession:async()=>{calls.push("export");return{cookies:[],origins:[]}}};}
