import { describe,expect,it } from "vitest";
import {
  AuthenticatedProfileService,ProfileEnvelopeCrypto,assertCapabilityUsable,issueAuthenticatedProfileCapability,
  projectAuthenticatedProfileForModel,type AuthAuditEvent,type AuthenticatedProfileRepository,type AuthenticatedSiteProfile,
  type AuthenticatedProfileOwnershipPolicy,type CredentialProfile,type SecretBlobStore
} from "../src/auth-profile";
import { AuthenticatedBootstrapError,AuthenticatedBrowserLifecycle,XAuthenticatedSiteAdapter,assertAuthenticatedReadOnlyAction } from "../src/authenticated-site";
import { BrowserNavigationError,PlaywrightBrowserAdapter } from "../src/browser";

const ROOT=Buffer.alloc(32,7).toString("base64");
class Blobs implements SecretBlobStore{values=new Map<string,Uint8Array>();async put(ref:string,value:Uint8Array){this.values.set(ref,value)}async get(ref:string){return this.values.get(ref)??null}async delete(ref:string){this.values.delete(ref)}}
class Repo implements AuthenticatedProfileRepository{credentials=new Map<string,CredentialProfile>();profiles=new Map<string,AuthenticatedSiteProfile>();audits:AuthAuditEvent[]=[];async createCredentialProfile(v:CredentialProfile){this.credentials.set(v.id,structuredClone(v))}async createSiteProfile(v:AuthenticatedSiteProfile){if(!this.profiles.has(v.id))this.profiles.set(v.id,structuredClone(v))}async getCredentialProfile(id:string){return structuredClone(this.credentials.get(id)??null)}async getSiteProfile(id:string){return structuredClone(this.profiles.get(id)??null)}async updateSiteProfile(v:AuthenticatedSiteProfile){this.profiles.set(v.id,structuredClone(v))}async appendAuthAudit(v:AuthAuditEvent){this.audits.push(structuredClone(v))}}
class Owners implements AuthenticatedProfileOwnershipPolicy{accounts=new Map([["account-a",{disabled:false}],["account-b",{disabled:false}]]);async assertActiveOwner(input:{tenantId:string;ownerId:string}){const account=this.accounts.get(input.ownerId);if(!account)throw new Error("AUTH_OWNER_NOT_FOUND");if(account.disabled)throw new Error("AUTH_OWNER_DISABLED");}}
const NOW=new Date("2026-09-16T00:00:00Z");
async function fixture(){const repository=new Repo();const blobs=new Blobs();const crypto=new ProfileEnvelopeCrypto({current:ROOT},"current");const owners=new Owners();const service=new AuthenticatedProfileService(repository,blobs,crypto,owners);const safe=await service.provision({tenantId:"account-a",ownerId:"account-a",siteFamily:"x",allowedOrigins:["https://x.com"],credential:{username:"secret-user@example.com",password:"correct horse battery staple"},now:NOW});const profile=(await repository.getSiteProfile(safe.authenticatedProfileId))!;return{repository,blobs,crypto,owners,service,safe,profile};}

describe("authenticated profile security",()=>{
  it("projects only opaque safe metadata and never returns credentials or blob references",async()=>{const f=await fixture();const output=JSON.stringify(f.safe);expect(output).not.toContain("secret-user");expect(output).not.toContain("correct horse");expect(output).not.toContain("credential.v1.enc");expect(projectAuthenticatedProfileForModel(f.profile)).toEqual(f.safe);expect(JSON.stringify(f.repository.audits)).not.toContain("correct horse");});
  it("encrypts credentials with an authenticated versioned envelope and tenant-bound context",async()=>{const f=await fixture();const bytes=[...f.blobs.values.values()][0];const persisted=new TextDecoder().decode(bytes);expect(persisted).not.toContain("correct horse");expect(JSON.parse(persisted)).toMatchObject({version:1,algorithm:"AES-256-GCM",keyId:"current"});const credential=await f.service.loadCredential(f.profile);expect(credential.password).toBe("correct horse battery staple");const ref=f.repository.credentials.get(f.profile.credentialProfileId!)!.encryptedCredentialRef;await expect(f.crypto.decrypt((await f.blobs.get(ref))!,{tenantId:"account-b",profileId:f.profile.credentialProfileId!,purpose:"credential"})).rejects.toMatchObject({code:"AUTH_SECRET_DECRYPTION_FAILED"});});
  it("rejects corrupted ciphertext without including secret values in the error",async()=>{const f=await fixture();const ref=f.repository.credentials.get(f.profile.credentialProfileId!)!.encryptedCredentialRef;const blob=(await f.blobs.get(ref))!;blob[blob.length-2]^=1;let message="";try{await f.service.loadCredential(f.profile)}catch(error){message=String(error)}expect(message).toContain("could not be decrypted");expect(message).not.toContain("correct horse");});
  it("binds capabilities to tenant, owner, run, generation, origin, version, expiry and revocation",async()=>{const f=await fixture();const cap=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:3,now:NOW,ttlMs:1000});const valid={tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:3,origin:"https://x.com",now:"2026-09-16T00:00:00.500Z"};expect(()=>assertCapabilityUsable(cap,f.profile,valid)).not.toThrow();expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,tenantId:"account-b"})).toThrow(/AUTH_TENANT_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,ownerId:"account-b"})).toThrow(/AUTH_OWNER_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,runId:"run-b"})).toThrow(/AUTH_RUN_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,browserGeneration:4})).toThrow(/AUTH_STALE_GENERATION/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,origin:"https://evil.example"})).toThrow(/AUTH_ORIGIN_DENIED/);expect(()=>assertCapabilityUsable(cap,f.profile,{...valid,now:"2026-09-16T00:00:02Z"})).toThrow(/AUTH_CAPABILITY_EXPIRED/);expect(()=>assertCapabilityUsable(cap,{...f.profile,version:2},valid)).toThrow(/AUTH_STALE_CAPABILITY/);expect(()=>assertCapabilityUsable(cap,{...f.profile,sessionState:"REVOKED",revokedAt:NOW.toISOString()},valid)).toThrow(/AUTH_PROFILE_REVOKED/);});
  it("persists and reuses encrypted browser state without loading credentials",async()=>{const f=await fixture();const state={cookies:[{name:"auth_token",value:"cookie-secret",domain:".x.com",path:"/",expires:2_000_000_000,httpOnly:true,secure:true,sameSite:"None" as const}],origins:[{origin:"https://x.com",localStorage:[{name:"session",value:"storage-secret"}]}]};const active=await f.service.saveSession(f.profile,state,{runId:"run-a",now:NOW});expect(active.sessionState).toBe("ACTIVE");expect(new TextDecoder().decode((await f.blobs.get(active.encryptedSessionRef!))!)).not.toContain("cookie-secret");await f.blobs.delete(f.repository.credentials.get(f.profile.credentialProfileId!)!.encryptedCredentialRef);await expect(f.service.loadSession(active)).resolves.toEqual(state);});
  it("durably records typed challenge, expiry and revocation transitions",async()=>{const f=await fixture();const mfa=await f.service.transition(f.profile,"MFA_REQUIRED",{runId:"run-a",reason:"x_human_verification",now:NOW});const expired=await f.service.transition(mfa,"SESSION_EXPIRED",{runId:"run-b",reason:"login_wall",now:NOW});const revoked=await f.service.transition(expired,"REVOKED",{now:NOW});expect(revoked).toMatchObject({sessionState:"REVOKED",version:4,revokedAt:NOW.toISOString()});expect(f.repository.audits.map(a=>a.toState)).toEqual(["REAUTH_REQUIRED","MFA_REQUIRED","SESSION_EXPIRED","REVOKED"]);});
  it("is retry-idempotent after encrypted credential persistence",async()=>{const f=await fixture();const again=await f.service.provision({tenantId:"account-a",ownerId:"account-a",siteFamily:"x",allowedOrigins:["https://x.com"],credential:{username:"replacement",password:"replacement-secret"},now:NOW});expect(again.authenticatedProfileId).toBe(f.profile.id);expect(f.repository.profiles.size).toBe(1);expect([...f.blobs.values.keys()].filter(key=>key.includes("credential"))).toHaveLength(1);});
  it("rejects tenant-owner mismatch, missing, disabled, and live-smoke owners before persistence",async()=>{const f=await fixture();const attempt=(tenantId:string,ownerId:string)=>f.service.provision({tenantId,ownerId,siteFamily:"x",allowedOrigins:["https://x.com"],credential:{username:"not-persisted",password:"not-persisted"},now:NOW});await expect(attempt("account-a","account-b")).rejects.toMatchObject({code:"AUTH_TENANT_OWNER_MISMATCH"});await expect(attempt("missing","missing")).rejects.toThrow(/AUTH_OWNER_NOT_FOUND/);await expect(attempt("live-smoke","live-smoke")).rejects.toThrow(/AUTH_OWNER_NOT_FOUND/);f.owners.accounts.get("account-b")!.disabled=true;await expect(attempt("account-b","account-b")).rejects.toThrow(/AUTH_OWNER_DISABLED/);expect(JSON.stringify([...f.blobs.values.values()])).not.toContain("not-persisted");});
});

describe("generic adapters and read-only policy",()=>{
  const x=new XAuthenticatedSiteAdapter();const snap=(url:string,visibleText:string,controls:Array<{role?:string;label:string;type?:string}>=[])=>({url,title:"X",visibleText,controls});
  it("classifies X authenticated, login, MFA, CAPTCHA and foreign-origin states",()=>{expect(x.detect(snap("https://x.com/home","For you Following"))).toMatchObject({state:"ACTIVE"});expect(x.detect(snap("https://x.com/i/flow/login","Log in to X"))).toMatchObject({state:"REAUTH_REQUIRED"});expect(x.detect(snap("https://x.com/i/flow/challenge","Enter the verification code"))).toMatchObject({state:"MFA_REQUIRED"});expect(x.detect(snap("https://x.com/account/access","Complete CAPTCHA"))).toMatchObject({state:"CHALLENGE_REQUIRED"});expect(x.detect(snap("https://evil.example/","X"))).toMatchObject({state:"CHALLENGE_REQUIRED"});});
  it("cannot perform state-changing authenticated operations",()=>{for(const action of ["post","reply","like","repost","follow","direct_message","settings","purchase"])expect(()=>assertAuthenticatedReadOnlyAction(action)).toThrow(/read-only/);for(const action of ["navigate","inspect","extract","scroll","follow_content_link"])expect(()=>assertAuthenticatedReadOnlyAction(action)).not.toThrow();});
  it("continues from identifier entry through a direct password field",async()=>{const {browser,calls}=bootstrapBrowser([snap("https://x.com/i/flow/login","Log in to X",[{role:"textbox",label:"Phone, email, or username",type:"text"},{role:"button",label:"Next"}]),snap("https://x.com/i/flow/login","Enter your password",[{role:"textbox",label:"Password",type:"password"},{role:"button",label:"Log in"}]),snap("https://x.com/home","For you Following")]);const result=await x.bootstrap(browser,{username:"user-secret",password:"password-secret"});expect(result).toMatchObject({state:"ACTIVE"});expect(calls).toEqual(["goto","fill:input[autocomplete=\"username\"]","control:button:Next","fill:input[type=\"password\"]","control:button:Log in"]);expect(JSON.stringify({result,calls})).not.toMatch(/user-secret|password-secret/);});
  it("selects an observed first-party password alternative before injecting the password",async()=>{const {browser,calls}=bootstrapBrowser([snap("https://x.com/i/flow/login","Log in to X",[{role:"textbox",label:"Phone, email, or username",type:"text"},{role:"button",label:"Next"}]),snap("https://x.com/i/flow/challenge","Check your email and enter the code",[{role:"button",label:"Use password instead"}]),snap("https://x.com/i/flow/login","Enter your password",[{role:"textbox",label:"Password",type:"password"},{role:"button",label:"Log in"}]),snap("https://x.com/home","For you Following")]);await expect(x.bootstrap(browser,{username:"user-secret",password:"password-secret"})).resolves.toMatchObject({state:"ACTIVE"});expect(calls).toContain("control:button:Use password instead");});
  it("stops on mandatory email code, MFA, CAPTCHA, and security challenge states",async()=>{expect(x.detect(snap("https://x.com/i/flow/challenge","Check your email and enter the code"))).toEqual({state:"MFA_REQUIRED",reason:"x_mandatory_email_code"});expect(x.detect(snap("https://x.com/i/flow/challenge","Enter the authentication code from your authenticator app"))).toEqual({state:"MFA_REQUIRED",reason:"x_mfa_required"});expect(x.detect(snap("https://x.com/i/flow/challenge","Complete CAPTCHA"))).toEqual({state:"CHALLENGE_REQUIRED",reason:"x_captcha"});expect(x.detect(snap("https://x.com/account/access","We detected unusual activity"))).toEqual({state:"CHALLENGE_REQUIRED",reason:"x_security_challenge"});});
  it("does not select password-like controls outside the trusted X auth surface",async()=>{const {browser,calls}=bootstrapBrowser([snap("https://evil.example/login","Check your email",[{role:"button",label:"Use password instead"}])]);await expect(x.bootstrap(browser,{username:"user-secret",password:"password-secret"})).resolves.toMatchObject({state:"CHALLENGE_REQUIRED",reason:"x_security_challenge"});expect(calls).toEqual(["goto"]);});
  it("fails safely when an alternative does not lead to a deterministic password route",async()=>{const {browser,calls}=bootstrapBrowser([snap("https://x.com/i/flow/login","Log in to X",[{role:"textbox",label:"Phone, email, or username",type:"text"},{role:"button",label:"Next"}]),snap("https://x.com/i/flow/challenge","Enter the verification code",[{role:"link",label:"Try another way"}]),snap("https://x.com/i/flow/challenge","Choose how to verify",[{role:"button",label:"Send SMS"}])]);await expect(x.bootstrap(browser,{username:"user-secret",password:"password-secret"})).rejects.toMatchObject({code:"PASSWORD_CONTROL_MISSING"});expect(calls).not.toContain('fill:input[type="password"]');});
  it.each([
    ["initial navigation",{goto:"fail"},"INITIAL_NAVIGATION_FAILED"],
    ["identifier injection",{fill:1},"IDENTIFIER_INJECTION_FAILED"],
    ["identifier submission",{control:1},"IDENTIFIER_SUBMISSION_FAILED"],
    ["password injection",{fill:2},"PASSWORD_INJECTION_FAILED"],
    ["password submission",{control:2},"PASSWORD_SUBMISSION_FAILED"]
  ] as const)("types %s failures without exposing credentials",async(_name,fault,code)=>{const browser=faultBrowser(fault);let caught:unknown;try{await x.bootstrap(browser,{username:"user-secret",password:"password-secret"})}catch(error){caught=error}expect(caught).toBeInstanceOf(AuthenticatedBootstrapError);expect(caught).toMatchObject({code});expect(JSON.stringify(caught)).not.toMatch(/user-secret|password-secret/);expect(browser.calls.filter(value=>value==="goto")).toHaveLength(1)});
  it.each(["NAVIGATION_TIMEOUT","NETWORK_POLICY_DENIED","UNEXPECTED_AUTH_ORIGIN"] as const)("preserves typed %s navigation failures",async code=>{const browser=faultBrowser({});browser.goto=async()=>{throw new BrowserNavigationError(code)};await expect(x.bootstrap(browser,{username:"user-secret",password:"password-secret"})).rejects.toMatchObject({code,stage:"navigation_started"});});
  it("types missing identifier/password controls and post-submit classification drift",async()=>{const missingIdentifier=bootstrapBrowser([snap("https://x.com/i/flow/login","Log in to X")]);await expect(x.bootstrap(missingIdentifier.browser,{username:"u",password:"p"})).rejects.toMatchObject({code:"IDENTIFIER_CONTROL_MISSING"});const missingPassword=bootstrapBrowser([snap("https://x.com/i/flow/login","Log in to X",[{role:"textbox",label:"Phone, email, or username",type:"text"},{role:"button",label:"Next"}]),snap("https://x.com/i/flow/login","Enter your password",[{role:"textbox",label:"Password",type:"password"}])]);await expect(x.bootstrap(missingPassword.browser,{username:"u",password:"p"})).rejects.toMatchObject({code:"PASSWORD_CONTROL_MISSING"});const drift=bootstrapBrowser([snap("https://x.com/i/flow/login","Log in to X",[{role:"textbox",label:"Phone, email, or username",type:"text"},{role:"button",label:"Next"}]),snap("https://x.com/i/flow/login","Enter your password",[{role:"textbox",label:"Password",type:"password"},{role:"button",label:"Log in"}]),snap("https://x.com/settings","Unknown")]);await expect(x.bootstrap(drift.browser,{username:"u",password:"p"})).rejects.toMatchObject({code:"AUTH_STATE_CLASSIFICATION_FAILED"});});
  it("stops bootstrap before password injection when a human challenge is present",async()=>{const calls:string[]=[];const browser={goto:async()=>{calls.push("goto")},fill:async(_selector:string,value:string)=>{calls.push(`fill:${value}`)},click:async()=>{calls.push("click")},clickControl:async()=>{calls.push("control")},snapshot:async()=>snap("https://x.com/account/access","Complete CAPTCHA"),importSession:async()=>{},exportSession:async()=>({cookies:[],origins:[]})};await expect(x.bootstrap(browser,{username:"user-secret",password:"password-secret"})).resolves.toMatchObject({state:"CHALLENGE_REQUIRED"});expect(calls).toEqual(["goto"]);});
  it("reuses an active encrypted session without loading or injecting credentials",async()=>{const f=await fixture();const active=await f.service.saveSession(f.profile,{cookies:[],origins:[]},{runId:"seed",now:NOW});const calls:string[]=[];const browser=fakeBrowser(calls,"ACTIVE");const capability=issueAuthenticatedProfileCapability(active,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const lifecycle=new AuthenticatedBrowserLifecycle(f.repository,f.service,browser as never,new Map([["x",x]]));await expect(lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"})).resolves.toMatchObject({sessionReused:true,detection:{state:"ACTIVE"}});expect(calls).toEqual(["attach","navigate","detect"]);});
  it("bootstraps only when no valid session exists and persists the resulting state",async()=>{const f=await fixture();const calls:string[]=[];const browser=fakeBrowser(calls,"ACTIVE");const capability=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const lifecycle=new AuthenticatedBrowserLifecycle(f.repository,f.service,browser as never,new Map([["x",x]]));const result=await lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"});expect(result).toMatchObject({sessionReused:false,detection:{state:"ACTIVE"},profile:{sessionState:"ACTIVE"}});expect(calls).toEqual(["establish","export"]);});
  it("types credential decryption, session capture, and session persistence failures",async()=>{const make=async()=>{const f=await fixture();const capability=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const input={capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"};return{f,input}};const decrypt=await make();const ref=decrypt.f.repository.credentials.get(decrypt.f.profile.credentialProfileId!)!.encryptedCredentialRef;(await decrypt.f.blobs.get(ref))![0]^=1;await expect(new AuthenticatedBrowserLifecycle(decrypt.f.repository,decrypt.f.service,fakeBrowser([],"ACTIVE") as never,new Map([["x",x]])).attach(decrypt.input)).rejects.toMatchObject({code:"CREDENTIAL_DECRYPTION_FAILED"});const capture=await make();const captureBrowser={...fakeBrowser([],"ACTIVE"),exportAuthenticatedSession:async()=>{throw new Error("cookie-secret")}};await expect(new AuthenticatedBrowserLifecycle(capture.f.repository,capture.f.service,captureBrowser as never,new Map([["x",x]])).attach(capture.input)).rejects.toMatchObject({code:"SESSION_CAPTURE_FAILED"});expect(capture.f.profile.sessionState).toBe("REAUTH_REQUIRED");const persist=await make();persist.f.repository.updateSiteProfile=async()=>{throw new Error("storage-secret")};await expect(new AuthenticatedBrowserLifecycle(persist.f.repository,persist.f.service,fakeBrowser([],"ACTIVE") as never,new Map([["x",x]])).attach(persist.input)).rejects.toMatchObject({code:"SESSION_PERSISTENCE_FAILED"});expect(JSON.stringify(persist.f.repository.audits)).not.toMatch(/cookie-secret|storage-secret/);});
  it("rejects use after the owning account is disabled or deleted",async()=>{const f=await fixture();const capability=issueAuthenticatedProfileCapability(f.profile,{tenantId:"account-a",ownerId:"account-a",runId:"run-a",browserGeneration:2,ttlMs:3_600_000});const lifecycle=new AuthenticatedBrowserLifecycle(f.repository,f.service,fakeBrowser([],"ACTIVE") as never,new Map([["x",x]]));f.owners.accounts.get("account-a")!.disabled=true;await expect(lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"})).rejects.toThrow(/AUTH_OWNER_DISABLED/);f.owners.accounts.delete("account-a");await expect(lifecycle.attach({capability,scope:{runId:"run-a",tenantId:"account-a",sessionId:"s",contextId:"c",generation:2},ownerId:"account-a"})).rejects.toThrow(/AUTH_OWNER_NOT_FOUND/);});
});

describe("authenticated bootstrap browser allocation diagnostics",()=>{
  it("types browser launch and context initialization failures and closes partial allocation",async()=>{const input={runId:"run-a",tenantId:"account-a",generation:1,allowedOrigins:["https://example.com"]};const launch=new PlaywrightBrowserAdapter({testOnlyPrivateNetwork:true,launchBrowser:async()=>{throw new Error("launch fixture")}});await expect(launch.allocate(input)).rejects.toMatchObject({code:"BROWSER_ALLOCATION_FAILED"});let closed=0;const context=new PlaywrightBrowserAdapter({testOnlyPrivateNetwork:true,launchBrowser:async()=>({newContext:async()=>{throw new Error("context fixture")},close:async()=>{closed++}} as never)});await expect(context.allocate(input)).rejects.toMatchObject({code:"BROWSER_CONTEXT_INITIALIZATION_FAILED"});expect(closed).toBe(1);});
});

function fakeBrowser(calls:string[],state:"ACTIVE"|"MFA_REQUIRED"){return{attachAuthenticatedSession:async()=>{calls.push("attach")},navigate:async()=>{calls.push("navigate")},detectAuthenticatedState:async()=>{calls.push("detect");return{state,reason:"fixture"}},establishAuthenticatedSession:async()=>{calls.push("establish");return{state,reason:"fixture"}},exportAuthenticatedSession:async()=>{calls.push("export");return{cookies:[],origins:[]}}};}
function bootstrapBrowser(snapshots:Array<{url:string;title:string;visibleText:string;controls:Array<{role?:string;label:string;type?:string}>}>){const calls:string[]=[];let index=0;return{calls,browser:{goto:async()=>{calls.push("goto")},fill:async(selector:string)=>{calls.push(`fill:${selector}`)},click:async(selector:string)=>{calls.push(`click:${selector}`)},clickControl:async(control:{role:"button"|"link";label:string})=>{calls.push(`control:${control.role}:${control.label}`);index++},snapshot:async()=>snapshots[index],importSession:async()=>{},exportSession:async()=>({cookies:[],origins:[]})}};}
function faultBrowser(fault:{goto?:string;fill?:number;control?:number}){const calls:string[]=[];let index=0,fill=0,control=0;const snapshots=[{url:"https://x.com/i/flow/login",title:"X",visibleText:"Log in to X",controls:[{role:"textbox",label:"Phone, email, or username",type:"text"},{role:"button",label:"Next"}]},{url:"https://x.com/i/flow/login",title:"X",visibleText:"Enter your password",controls:[{role:"textbox",label:"Password",type:"password"},{role:"button",label:"Log in"}]},{url:"https://x.com/home",title:"X",visibleText:"For you Following",controls:[]}];return{calls,goto:async()=>{calls.push("goto");if(fault.goto)throw new Error("fixture")},fill:async()=>{fill++;calls.push("fill");if(fault.fill===fill)throw new Error("fixture")},click:async()=>{},clickControl:async()=>{control++;calls.push("control");if(fault.control===control)throw new Error("fixture");index++},snapshot:async()=>snapshots[index],importSession:async()=>{},exportSession:async()=>({cookies:[],origins:[]})};}
