import {describe,expect,it} from "vitest";
import {ChallengeCoordinator,DetectOnlyBrowserChallengeProvider,DeterministicTestChallengeProvider,InMemoryAuthenticationChallengeStore,assertProductionChallengeProvider,type AuthenticationChallengeRecord,type AuthenticationChallengeState} from "../src/challenge-coordinator";
import {makeId} from "../src/contracts";

const binding={runId:"run-a",bootstrapRequestId:"bootstrap-a",tenantId:"tenant-a",ownerId:"owner-a",profileId:"profile-a",profileVersion:3,browserGeneration:2,authFlowId:"flow-a",expiresAt:"2999-01-01T00:00:00.000Z"};
const input=(overrides:Record<string,unknown>={})=>({...binding,kind:"CAPTCHA" as const,phase:"PRE_IDENTIFIER" as const,validateFences:async()=>true,reobserve:async()=>({challengePresent:false,surfaceKind:"IDENTIFIER_ENTRY_READY"}),...overrides});

class TracingStore extends InMemoryAuthenticationChallengeStore{states:AuthenticationChallengeState[]=[];override async create(record:AuthenticationChallengeRecord){const value=await super.create(record);if(this.states.length===0)this.states.push(value.state);return value}override async transition(id:string,expected:readonly AuthenticationChallengeState[],update:Partial<AuthenticationChallengeRecord>){const value=await super.transition(id,expected,update);this.states.push(value.state);return value}}

describe("provider-neutral authenticated challenge coordination",()=>{
  it("re-observes a persistent challenge before recording unsupported capability",async()=>{const store=new TracingStore();let observations=0;const result=await new ChallengeCoordinator(store,new DetectOnlyBrowserChallengeProvider("cloudflare_browser"),{wait:async()=>{}}).coordinate(input({reobserve:async()=>{observations++;return{challengePresent:true,surfaceKind:"CAPTCHA"}}}));expect(result).toMatchObject({mayContinue:false,record:{challengeKind:"CAPTCHA",state:"UNSUPPORTED",providerKind:"cloudflare_browser",attemptBudget:1,attemptNumber:0,resolutionOutcome:"DETECT_ONLY_AFTER_REOBSERVATION"}});expect(observations).toBe(2);expect(store.states).toEqual(["DETECTED","CHALLENGE_HANDLING","UNSUPPORTED"])});
  it("resumes automatically when a transient challenge clears under trusted re-observation",async()=>{const store=new TracingStore();let observations=0;const result=await new ChallengeCoordinator(store,new DetectOnlyBrowserChallengeProvider("self_hosted_chromium"),{wait:async()=>{}}).coordinate(input({reobserve:async()=>({challengePresent:++observations<2,surfaceKind:observations<2?"CAPTCHA":"IDENTIFIER_ENTRY_READY"})}));expect(result).toMatchObject({mayContinue:true,record:{state:"RESOLVED",resolutionOutcome:"REOBSERVED_CLEAR",subsequentSurfaceKind:"IDENTIFIER_ENTRY_READY"}});expect(store.states).toEqual(["DETECTED","CHALLENGE_HANDLING","RESOLVED"])});
  it("moves through requested and resolving before mandatory clear re-observation",async()=>{const store=new TracingStore();let reobserved=0;const result=await new ChallengeCoordinator(store,new DeterministicTestChallengeProvider(1),{wait:async()=>{}}).coordinate(input({reobserve:async()=>{reobserved++;return{challengePresent:false,surfaceKind:"IDENTIFIER_ENTRY_READY"}}}));expect(result).toMatchObject({mayContinue:true,record:{state:"RESOLVED",attemptNumber:1,resolutionOutcome:"REOBSERVED_CLEAR",subsequentSurfaceKind:"IDENTIFIER_ENTRY_READY"}});expect(store.states).toEqual(["DETECTED","RESOLUTION_REQUESTED","RESOLVING","RESOLVED","RESOLVED"]);expect(reobserved).toBe(1)});
  it("does not proceed when provider reports resolved but the challenge remains",async()=>{const result=await new ChallengeCoordinator(new TracingStore(),new DeterministicTestChallengeProvider(0)).coordinate(input({reobserve:async()=>({challengePresent:true,surfaceKind:"CAPTCHA"})}));expect(result).toMatchObject({mayContinue:false,record:{state:"FAILED",resolutionOutcome:"CHALLENGE_STILL_PRESENT",subsequentSurfaceKind:"CAPTCHA"}})});
  it("expires within the bounded resolution deadline",async()=>{const result=await new ChallengeCoordinator(new TracingStore(),new DeterministicTestChallengeProvider(10),{overallTimeoutMs:0,wait:async()=>{}}).coordinate(input());expect(result).toMatchObject({mayContinue:false,record:{state:"EXPIRED",resolutionOutcome:"RESOLUTION_TIMEOUT"}})});
  it("bounds a stalled provider request independently",async()=>{const provider=new DeterministicTestChallengeProvider(1);provider.beginResolution=async()=>new Promise(()=>{});const result=await new ChallengeCoordinator(new TracingStore(),provider,{providerRequestTimeoutMs:1}).coordinate(input());expect(result).toMatchObject({mayContinue:false,record:{state:"FAILED",resolutionOutcome:"PROVIDER_REQUEST_FAILED"}})});
  it.each(["browser generation","profile version"])("rejects stale %s fencing",async()=>{const result=await new ChallengeCoordinator(new TracingStore(),new DeterministicTestChallengeProvider(0)).coordinate(input({validateFences:async()=>false}));expect(result).toMatchObject({mayContinue:false,record:{state:"CANCELLED",resolutionOutcome:"FENCE_REJECTED"}})});
  it("is idempotent across duplicate delivery and does not duplicate physical resolution",async()=>{const store=new TracingStore();let begins=0;const provider=new DeterministicTestChallengeProvider(0);const original=provider.beginResolution.bind(provider);provider.beginResolution=async value=>{begins++;return original(value)};const coordinator=new ChallengeCoordinator(store,provider);await coordinator.coordinate(input());await coordinator.coordinate(input());expect(begins).toBe(1);expect([...store.records.values()]).toHaveLength(1)});
  it("recovers a provider-resolved record by re-observing rather than assuming clearance",async()=>{const store=new TracingStore();const coordinator=new ChallengeCoordinator(store,new DeterministicTestChallengeProvider(0));const first=await coordinator.coordinate(input({reobserve:async()=>({challengePresent:true,surfaceKind:"CAPTCHA"})}));expect(first.record.state).toBe("FAILED");const second=await coordinator.coordinate(input());expect(second.mayContinue).toBe(false)});
  it.each(["DETECTED","RESOLUTION_REQUESTED","RESOLVING","RESOLVED"] as const)("recovers after a crash at %s without bypassing re-observation",async state=>{const store=new TracingStore();const challengeId=makeId("auth_challenge",binding.bootstrapRequestId,binding.runId,binding.profileId,binding.profileVersion,binding.browserGeneration,binding.authFlowId,"CAPTCHA","PRE_IDENTIFIER");await store.create({...binding,challengeId,challengeKind:"CAPTCHA",challengePhase:"PRE_IDENTIFIER",providerKind:"deterministic_test",observedAt:"2026-01-01T00:00:00.000Z",attemptBudget:1,attemptNumber:state==="DETECTED"?0:1,state,providerOperationId:state==="RESOLVING"||state==="RESOLVED"?`test_operation_${challengeId}`:undefined,updatedAt:"2026-01-01T00:00:00.000Z",elapsedMs:0});let observed=0;const result=await new ChallengeCoordinator(store,new DeterministicTestChallengeProvider(state==="RESOLUTION_REQUESTED"?0:1),{wait:async()=>{}}).coordinate(input({reobserve:async()=>{observed++;return{challengePresent:false,surfaceKind:"IDENTIFIER_ENTRY_READY"}}}));expect(result.mayContinue).toBe(true);expect(observed).toBe(1)});
  it("cancels provider work when the caller aborts",async()=>{const controller=new AbortController();controller.abort(new Error("cancelled"));const result=await new ChallengeCoordinator(new TracingStore(),new DeterministicTestChallengeProvider()).coordinate(input({signal:controller.signal}));expect(result).toMatchObject({record:{state:"CANCELLED",resolutionOutcome:"CANCELLED"},mayContinue:false})});
  it("keeps secrets, solutions, tokens, and raw content out of durable records",async()=>{const store=new TracingStore();await new ChallengeCoordinator(store,new DetectOnlyBrowserChallengeProvider("cloudflare_browser")).coordinate(input());expect(JSON.stringify([...store.records.values()])).not.toMatch(/raw-captcha-bytes|answer-secret|cookie-secret|provider-token-secret|iframe-secret/i)});
  it("rejects deterministic test resolution in production composition",()=>{expect(()=>assertProductionChallengeProvider(new DeterministicTestChallengeProvider())).toThrow(/test challenge provider/);expect(()=>assertProductionChallengeProvider(new DetectOnlyBrowserChallengeProvider("cloudflare_browser"))).not.toThrow()});
});
